### PR TITLE
WASAPI: Recover after the device is reconfigured or leaves exclusive mode.

### LINKED ISSUE #15758: NVDA fails and does not recover when when all audio devices become unavailable
### Steps to reproduce:
* Switch NVDA to wasapi;
* When NVDA is working normaly open sound card driver settings and change sample rate;
* Or else very fastly disconnect and connect your sound card again;
* Important: this is a third-party sound card, not realtek.

### Actual behavior:
NVDA stops speaking and spams with error sounds on every key press or any speech output.

### Expected behavior:
NVDA should handle those reconnects or configuration changes correctly.

### NVDA logs, crash dumps and other attachments:
[nvda-old.log](https://github.com/nvaccess/nvda/files/13300293/nvda-old.log)

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
NVDA alpha-29899,cb356535 (2024.1.0.29899)
Also reproduceable on any NVDA version which supports wasapi.

#### Windows version:
Windows 11 23H2 (AMD64) build 22631.2506
Also was reproduceable on Windows 10.

#### Name and version of other software in use when reproducing the issue:
Not applicable.

#### Other information about your system:
Sound card is an USB-microphone with output. Model is sE Electronics NEOM USB

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. Reproduceable on any NVDA which supports wasapi.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

### LINKED ISSUE #15775: WASAPI: Error if NVDA produces speech while another app is in "Exclusive mode"
### Steps to reproduce:
Have your audio device configured to grant WASAPI "exclusive mode".
Start an app that can use exclusive mode, such as foobar2000.
While you're playing something in exclusive mode, also do something that will generate speech.
When you stop the playback, when NVDA should make sounds, the error sound plays.
This is not synth dependent, tested with OneCore and ESpeak.
It is a rare issue, so in my opinion not high priority, but attempting to fix it might improve the audio stability.

### Actual behavior:

Error sound plays, whatever action you make.

### Expected behavior:

Speech should resume as normal.

### NVDA logs, crash dumps and other attachments:
NVDA log attached.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Latest alpha (but has had the same behavior since the change to WASAPI).

#### Windows version:
Windows 11 23H2

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, has been present since WASAPI was introduced

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
[nvda-wex.log](https://github.com/nvaccess/nvda/files/13327809/nvda-wex.log)

### PR DESCRIPTION
**Pull request by jcsteh**
### Link to issue number:
Fixes #15758. Fixes #15775.

### Summary of the issue:
When another application takes exclusive control of NVDA's audio output device, NVDA can no longer speak. There's nothing we can do about this and it's reasonable that we log errors in this case. However, previously, when the other application released exclusive control of the device, NVDA would still fail to speak. Similar behaviour has been observed when the sampling rate is changed with certain audio drivers.

### Description of user facing changes
NVDA now resumes audio if the configuration of the output device changes or another application releases exclusive control of the device.

### Description of development approach
1. In WasapiPlayer::feed, as well as attempting reopen for AUDCLNT_E_DEVICE_INVALIDATED, reopen also for AUDCLNT_E_NOT_INITIALIZED. This handles the case that we tried to reopen previously due to an invalidated device and failed.
2. In WasapiPlayer::stop, if either of these error codes is returned by WASAPI, just ignore them. The device is clearly stopped anyway. Previously, these errors got propagated to Python, which broke SpeechManager and stopped speech from being attempted at all. That in turn meant that feed was never called and thus reopen was never attempted.
3. In WasapiPlayer::feed's reopenUsingNewDev, the hr result code was being accidentally shadowed and thus never returned to the caller. This meant that reopen failures were never raised as exceptions and thus never logged. This has now been fixed.
4. Previously, due to an oversight, we weren't setting the ctypes restype for wasPlay_open. This meant that errors from this function were silently ignored. This is really a bit of drive-by cleanup and isn't necessary to fix this bug, but should make debugging easier if we hit problems here in future.

### Testing strategy:
1. Configured REAPER to use WASAPI exclusive mode.
2. Confirmed that NVDA couldn't speak.
3. Exited REAPER.
4. Confirmed that NVDA could speak again. Before this change, it just logged lots of exceptions until restarted.

I can't reproduce the device reconfiguration problem myself, so I can't test it. However, @kirill-jjj, who reported #15758, has tested it and confirmed that it works as per https://github.com/nvaccess/nvda/pull/15783#issuecomment-1811059003.

### Known issues with pull request:
None.

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by kirill-jjj** [comment]
Works good for me.

File: nvdaHelper/local/wasapi.cpp [hunk 1]
```diff
@@ -351,9 +351,11 @@ HRESULT WasapiPlayer::feed(unsigned char* data, unsigned int size,
 				}
 			}
 			hr = client->GetCurrentPadding(&paddingFrames);
-			if (hr == AUDCLNT_E_DEVICE_INVALIDATED) {
-				// If we're using a specific device, it's just been invalidated. Fall back
-				// to the default device.
+			if (hr == AUDCLNT_E_DEVICE_INVALIDATED ||
+					hr == AUDCLNT_E_NOT_INITIALIZED) {
```
Comment (seanbudd) [inline nvdaHelper/local/wasapi.cpp:355]: Lint for readability

```suggestion
			if (
				hr == AUDCLNT_E_DEVICE_INVALIDATED
				|| hr == AUDCLNT_E_NOT_INITIALIZED
			) {
```

File: nvdaHelper/local/wasapi.cpp [hunk 2]
```diff
@@ -522,12 +524,18 @@ bool WasapiPlayer::didPreferredDeviceBecomeAvailable() {
...
-		return hr;
-	}
-	hr = client->Reset();
-	if (FAILED(hr)) {
-		return hr;
+	// If the device has been invalidated, it has already stopped. Just ignore
+	// this and behave as if we were successful to avoid a cascade of breakage.
+	// feed() will attempt to reopen the device next time it is called.
+	if (hr != AUDCLNT_E_DEVICE_INVALIDATED &&
+			hr != AUDCLNT_E_NOT_INITIALIZED) {
```
Comment (seanbudd) [inline nvdaHelper/local/wasapi.cpp:531]:
```suggestion
	if (
		hr != AUDCLNT_E_DEVICE_INVALIDATED
		&& hr != AUDCLNT_E_NOT_INITIALIZED
	) {
```

**Review by seanbudd — APPROVED** [review]
Thanks @jcsteh
