### PR TITLE
I8438 fix ordered list start number in ie

### LINKED ISSUE #8438: Ordered list numbering always starts from number 1 without regard to type or start attribute in internet explorer
### Steps to reproduce:
1. Open the attached test file in internet explorer.
 2. go to the list under second heading "Next Set".
3. the list numbering should start with number 4 which can be confirmed by opening the same file in google Chrome or Firefox.

### Actual behavior:

The list numbering does not follow start and type attribute. if type attribute suggests alphabets through "a" or "A" or if it suggests roman numeral with "i" or "I", there is no difference

### Expected behavior:

NVDA should read the numbering properly.

Fixing this issue is also important as internet control is used by some software in which case users ccan not switch to Google Chrome or Firefox. One example is vital source.

understanding these numbers is important as question and answers could be numbered with breaks in between and users need to check the corresponding entries.

### System configuration:

Windows 7 

#### NVDA Installed/portable/running from source:
Installed and portable

#### NVDA version:
2018.1.1 and 2018.2
#### Windows version:
Windows 7
#### Name and version of other software in use when reproducing the issue:

Internet explorer 11, Google Chrome, and Firefox.
#### Other information about your system:

[OLHTML.zip](https://github.com/nvaccess/nvda/files/2132668/OLHTML.zip)

### PR DESCRIPTION
**Pull request by feerrenrut**
### Link to issue number:
handles review actions for (and supersedes) #8474
fixes #8438

### Summary of the issue:
1. In IE NVDA was not reading list item numbers for ordered list if the number is specified in start attribute.
1. NVDA also does not handle the `type` attribute that specifies what type of numbers should be shown. 

Example:
``` html
<ol start="50">
  <li>Coffee</li>
  <li>items<ol type="A">
  	<li>thing</li>
  	<li>another thing</li>
  </ol></li>
  <li>Tea</li>
  <li>Milk</li>
</ol>
```

### Description of how this pull request fixes the issue:
- The start attribute is now observed for IE, fixing the first issue.
- The second issue is not considered as important, since the ordering information is announced, I.E. a number is read instead of the letter, or roman numeral. This is essentially a presentation issue, and matches what happens for unordered lists where "bullet" is read regardless of the level or bullet type.

### Testing performed:
In IE I explored ordered lists, unordered lists, combinations, with and without the start and type attribute

### Known issues with pull request:
None

### Change log entry:

Bug fixes
`In Internet Explorer, numbers are now announced correctly for ordered lists if the list does not start with 1. (#8438)`

### CODE REVIEW

**Review by michaelDCurran — APPROVED** [review]

File: nvdaHelper/vbufBackends/mshtml/mshtml.cpp [hunk 1]
```diff
@@ -454,6 +454,9 @@ inline void getAttributesFromHTMLDOMNode(IHTMLDOMNode* pHTMLDOMNode,wstring& nod
 		macro_addHTMLAttributeToMap(L"colspan",false,pHTMLAttributeCollection2,attribsMap,tempVar,tempAttribNode);
 		macro_addHTMLAttributeToMap(L"rowspan",false,pHTMLAttributeCollection2,attribsMap,tempVar,tempAttribNode);
 		macro_addHTMLAttributeToMap(L"scope",false,pHTMLAttributeCollection2,attribsMap,tempVar,tempAttribNode);
+	} else if (nodeName.compare(L"OL") == 0) {
+		macro_addHTMLAttributeToMap(L"start", false, pHTMLAttributeCollection2, attribsMap, tempVar, tempAttribNode);
+		macro_addHTMLAttributeToMap(L"type", false, pHTMLAttributeCollection2, attribsMap, tempVar, tempAttribNode);
```
Comment (feerrenrut) [inline nvdaHelper/vbufBackends/mshtml/mshtml.cpp:459]: Looks like we don't need this, I'll remove it.
