### PR TITLE
Revert live region changes to mshtml virtual buffer

### LINKED ISSUE #11834: `ui.browseableMessage()` broken since alpha-21356,ae4ea8f9
### Steps to reproduce:
1. Open the NVDA Python console (default: NVDA+CTRL+z).
2. Execute the following instructions:
   `import ui;ui.browseableMessage("This is a test!", "Test")`

### Actual behavior:
NVDA crashes with the following in the log:

```
CRITICAL - watchdog._crashHandler (07:43:28.223) - Dummy-5 (12140):
NVDA crashed! Minidump written to C:\Users\andre\AppData\Local\Temp\nvda.log\..\nvda_crash.dmp
INFO - watchdog._crashHandler (07:43:30.437) - Dummy-5 (12140):
Listing stacks for Python threads:
Python stack for thread 12140 (Dummy-5):
  File "watchdog.pyc", line 213, in _crashHandler
  File "watchdog.pyc", line 63, in getFormattedStacksForAllThreads

Python stack for thread 4144 (virtualBuffers.MSHTML.VirtualBuffer.loadBuffer):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "virtualBuffers\__init__.pyc", line 444, in _loadBuffer

Python stack for thread 10748 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x05BCACD8>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 332, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 12044 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 120, in _watcher

Python stack for thread 10612 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 79, in hookThreadFunc

Python stack for thread 7352 (_UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "_UIAHandler.pyc", line 315, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 3700 (braille._BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "braille.pyc", line 2187, in func

Python stack for thread 13092 (MainThread):
  File "nvda.pyw", line 247, in <module>
  File "core.pyc", line 568, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1062, in Notify
  File "core.pyc", line 538, in run
  File "queueHandler.pyc", line 88, in pumpAll
  File "queueHandler.pyc", line 55, in flushQueue
  File "eventHandler.pyc", line 65, in _queueEventCallback
  File "eventHandler.pyc", line 241, in executeEvent
  File "eventHandler.pyc", line 284, in doPreGainFocus
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1121, in event_focusEntered
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 517, in getObjectSpeech
  File "speech\__init__.pyc", line 381, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 762, in _get_name
  File "comtypes\__init__.pyc", line 857, in __call__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

INFO - watchdog._crashHandler (07:43:30.438) - Dummy-5 (12140):
Restarting due to crash
```

### Expected behavior:
No crash.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-21359,aecff99a

#### Windows version:
10 Insider (64-bit) build 20251.1

#### Name and version of other software in use when reproducing the issue:
Reproducible with NVDA+f when quickly pressed two times in Word, Firefox, etc. And in a lot of other situations.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Bug introduced in a recent alpha build.

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Fixes #11834

### Summary of the issue:
Changes in #9079 caused crashes in the virtual buffer code when viewing a browsable message.

### Description of how this pull request fixes the issue:
Revert the MSHTML changes from #9079. This means that we're still using the new live region code in Firefox and Chrome. While this introduces an inconsistency, I think there are several justifications.

1. The mshtml vbuf is used less frequently than the Gecko vbuf
2. I'm intending to investigate the issue, though I'm not at all skilled to operate a debugger with NVDA. But at least, we now have an easy method to trigger the issue.

### Testing performed:
Tested that browseable messages no longer crash.

### Known issues with pull request:
None

### Change log entry:
In pr, as it modifies an existing entry.

### CODE REVIEW

File: nvdaHelper/vbufBackends/mshtml/node.cpp [hunk 1]
```diff
@@ -124,15 +124,7 @@ class CDispatchChangeSink : public IDispatch {
...
-			if (
-				this->storageNode->ariaLiveNode
-				&& this->storageNode->ariaLiveNode != this->storageNode
-				&& !this->storageNode->ariaLiveIsBusy
-				&& (
-					this->storageNode->ariaLiveIsTextRelevant
-					|| this->storageNode->ariaLiveIsAdditionsRelevant
-				)
-			) {
+			if(this->storageNode->ariaLiveNode&&this->storageNode->ariaLiveNode!=this->storageNode&&!this->storageNode->ariaLiveIsBusy&&(this->storageNode->ariaLiveIsTextRelevant||this->storageNode->ariaLiveIsAdditionsRelevant)) {
```
Comment (Andre9642) [inline nvdaHelper/vbufBackends/mshtml/node.cpp:127]: I think that it's better to Split long if statements onto several lines. Do you have a reason to change this here and others places?

**Review by AAClause — COMMENTED** [review]
Thank for the fix. I tested the try build, issue solved for me! :)

File: nvdaHelper/vbufBackends/mshtml/node.h [hunk 2]
```diff
@@ -1,7 +1,7 @@
 /*
 This file is a part of the NVDA project.
 URL: http://www.nvda-project.org/
-Copyright 2006-2020 NV Access Limited, Google LLC, Leonard de Ruijter
+Copyright 2006-2015 NVDA contributers.
```
Comment (Andre9642) [inline nvdaHelper/vbufBackends/mshtml/node.h:4]:
```suggestion
Copyright 2006-2015 NVDA contributors.
```

File: nvdaHelper/vbufBackends/mshtml/node.cpp [hunk 3]
```diff
@@ -407,13 +384,13 @@ void MshtmlVBufStorage_controlFieldNode_t::preProcessLiveRegion(const MshtmlVBuf
 	} else {
 		this->ariaLiveAtomicNode=parent?parent->ariaLiveAtomicNode:NULL;
 	}
-	LOG_DEBUG(L"preProcessLiveRegion: ariaLiveNode "<<ariaLiveNode<<L", ariaLiveIsTextRelevant "<<ariaLiveIsTextRelevant<<L", ariaLiveIsAdditionsRelevant "<<ariaLiveIsAdditionsRelevant<<L", ariaLiveIsBusy "<<ariaLiveIsBusy<<L", ariaLiveAtomicNode "<<ariaLiveAtomicNode);
```
Comment (Andre9642) [inline nvdaHelper/vbufBackends/mshtml/node.cpp:410]: I assume that this line should be restored and the (new) comment should be removed

**Comment by leonardder** [comment]
Note that this pr simply reverts the changes done in #9079, it simply brings back the code to the state it had in NVDA 2020.3. I personally would like to leave this as is.

**Comment by feerrenrut** [comment]
Ok, lets revert this, hopefully we can get to the bottom of the issue via #11834 in order to bring IE back into line.

**Review by feerrenrut — APPROVED** [review]
