### PR TITLE
Work around crash in Google Chrome when navigating tweets on twitter.com

### LINKED ISSUE #8777: Crash in Google Chrome when navigating tweets on twitter.com
### Steps to reproduce:
With NVDA 2018.3 or newer:
1. Open Google Chrome.
2. Go to www.twitter.com/ and log in if necessary.
3. Arrow down to the tweets in your timeline.
4. Switch off NVDA's single leter navigation with NVDA+shift+space.
5. Press Twitter's j and k tweet navigation shortcut keys to move between the tweets.

### Actual behavior:
Google Chrome crashes.

### Expected behavior:
Google Chrome should not crash.

### Technical details
Some of the nodes in the tweets contain multiple labelledBy relations. As NVDA must fetch at least the first labelledBy relation on any given node to work out whether the accessible label is visible somewhere else on the page, NVDA calls IAccessible2_2::get_relationTargetsOfType with relationType of IA2_RELATION_LABELLED_BY and maxTargets of 1.
 However, there seems to be a bug in Google Chrome's implementation of relationTargetsOfType that causes a buffer overrun. In short, Chrome allocates a buffer suitable to fit maxTargets, but then fills it with the total number of relation targets for the node. If the total number of targets is greater than maxTargets, then Chrome overruns the buffer and eventually causes heap corruption.

This 
[Uploading dynamic multiple labelled by.html.txt…](simplified testcase) when run in Chrome specifically shows the crash. Load the page, and then press the 'show' button. This causes a text input field to appear that has 4 labelled by relations on it.

Chrome version: 69.0.3497.100 (Official Build) (64-bit) (cohort: Stable)

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
Fixes #8777 

### Summary of the issue:
Google Chrome crashes when navigating tweets in twitter.com due to a buffer overrun in Chrome's implementation of IAccessible2_2::relationTargetsOfType.
NVDA started calling relationTargetsOfType in pr #8352. 

### Description of how this pull request fixes the issue:
This PR works around the crash by making use of the fact that chrome's relationTargetsOftype works okay when requesting all targets (numRelations is 0) rather than a specific number of them that may be smaller than the total amount.

### Testing performed:
Tested NVDA and Chrome using the testcases in #8777.
And again with tests in pr #8352  

 ### Known issues with pull request:
None.

### Change log entry:
Already in PR.

### CODE REVIEW

**Comment by michaelDCurran** [comment]
As this causes a crash, introduced in the 2018.3 release cycle, this should be  made available in a 2018.3 minor release.
@feerrenrut  could you please review this with priority so I can release an rc and then 2018.3.2.

File: nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp [hunk 1]
```diff
@@ -30,10 +30,18 @@ This license can be found at:
...
 	IUnknown** ppUnk=nullptr;
 	long nTargets=0;
-	constexpr int numRelations=2;
+	// We only need to request one relation target
+	int numRelations=1;
+	// However, a bug in Chrome causes a buffer overrun if numRelations is less than the total number of targets the node has.
+	// Therefore, If this is Chrome, request all targets (by setting numRelations to 0) as this works around the bug.
+	// There is no major performance hit to fetch all targets in Chrome as Chrome is already fetching all targets either way.
+	// In Firefox there would be extra cross-proc calls.
+	if(this->toolkitName.compare(L"Chrome")==0) {
```
Comment (feerrenrut) [inline nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp]: `toolkitName` might be null. This function should probably check for this.

**Review by feerrenrut — CHANGES_REQUESTED** [review]

**Comment by michaelDCurran** [comment]
toolkitName is an std::wstring. It could be empty, but never null.

compare simply won't return 0 if it is empty.

**Comment by feerrenrut** [comment]
Oh, of course it is. But then its assigned from a `BSTR`, I think this needs to be:
```
this->toolkitName = std::wstring(toolkitName, SysStringLen(toolkitName));
```
Check https://stackoverflow.com/a/6284978

**Comment by michaelDCurran** [comment]
Done now.

**Review by feerrenrut — APPROVED** [review]
