### PR TITLE
Stop crashing hh.exe when passing strings to MSHTML

### LINKED ISSUE #8976: NVDA 2018.4 beta 1 not reading .chm file
Using NVDA 2018.4 beta 1 on Windows 10 and trying to open the AutoHotKey help file.  Contents momentarily appears on the screen but NVDA says nothing.  There is then that nasty clang-clang sound and I am returned to where I started.  The problem does not occur with earlier NVDA versions, including nvda_snapshot_alpha-16247,fbae6b0b.  Also no problem when using Narrator.  A copy of the log file is attached.
[nvda-log.txt](https://github.com/nvaccess/nvda/files/2612149/nvda-log.txt)
Andrew

### PR DESCRIPTION
**Pull request by michaelDCurran**
Aiming for 2018.4rc2 as this is a crash.

### Link to issue number:
Closes #8976 

### Summary of the issue:
Similar to issue #8759 where Firefox was crashing when passing a string literal to a COM method, hh.exe when opening particular chm files would also crash.
Again, we are passing a string literal to a COM method, this time in the MSHTML vbufBackend.
Passing a string literal in place of a bstr is bad as the COM marshaller tries to look for the bstr prefix containing the length, and either causes a memory violation or finds junk.
This only however seems to cause a crash in optimized builds of NVDA, and only with very recent versions of Visual Studio 2017, as this particular crash has not been seen before beta1 of 2018.4.
 
### Description of how this pull request fixes the issue:
Similar to pr #8767, the string literal is first converted to a BSTR before passing to the COM method.
This PR also adds a rule to the appveyor config that allows us us to build optimized try builds  when a branch name starts with try-release-. This change made it easier to test this fix.

### Testing performed:
While running an optimized try build for this pr, opened the chm in issue #8759 and it did not crash.
Also opened several pages in Internet Explorer to ensure that generally NVDA was still getting all required information from MSHTML.
Try build has been provided on the issue, awaiting testing by original reporter. 

### Known issues with pull request:
None.

### Change log entry:
None.

### CODE REVIEW

File: nvdaHelper/vbufBackends/mshtml/mshtml.cpp [hunk 1]
```diff
@@ -401,8 +402,11 @@ inline void getCurrentStyleInfoFromHTMLDOMNode(IHTMLDOMNode* pHTMLDOMNode, bool&
 	if (pHTMLCurrentStyle) pHTMLCurrentStyle->Release();
 }
 
+// #8976: the string in the following macro  must be passed to the COM method as a BSTR 
+// otherwise the COM marshaller will try and read the BSTR length and hit either inaccessible memory or get back junk. 
+// This is seen in optimized builds of NVDA when accessing some CHM files in hh.exe.
 #define macro_addHTMLAttributeToMap(attribName,allowEmpty,attribsObj,attribsMap,tempVar,tempAttrObj) {\
```
Comment (feerrenrut) [inline nvdaHelper/vbufBackends/mshtml/mshtml.cpp]: I guess this has probably been a macro for a while. I'd be quite tempted to turn it into a regular function, the benefits of doing so is to make them more easy to debug, and to get rid of the backslashes.

File: nvdaHelper/vbufBackends/mshtml/mshtml.cpp [hunk 2]
```diff
@@ -401,8 +402,11 @@ inline void getCurrentStyleInfoFromHTMLDOMNode(IHTMLDOMNode* pHTMLDOMNode, bool&
 	if (pHTMLCurrentStyle) pHTMLCurrentStyle->Release();
 }
 
+// #8976: the string in the following macro  must be passed to the COM method as a BSTR 
+// otherwise the COM marshaller will try and read the BSTR length and hit either inaccessible memory or get back junk. 
+// This is seen in optimized builds of NVDA when accessing some CHM files in hh.exe.
 #define macro_addHTMLAttributeToMap(attribName,allowEmpty,attribsObj,attribsMap,tempVar,tempAttrObj) {\
-	attribsObj->getNamedItem(attribName,&tempAttrObj);\
+	attribsObj->getNamedItem(CComBSTR(attribName),&tempAttrObj);\
```
Comment (feerrenrut) [inline nvdaHelper/vbufBackends/mshtml/mshtml.cpp]: Is there anything we can do to look for other places this bug might exist?

**Review by feerrenrut — APPROVED** [review]

**Comment by leonardder** [comment]
This branch is filed against master. I also found out that the rc branch still seems to be at 2018.3.2.

I think that the rc branch has to be updated based on the 2018.4-rc1 tag, and then we can switch branches for this pr.
