### PR TITLE
Switch import table hooks to detours

### LINKED ISSUE #13335: NVDA also crashes and exits when an error occurs in the application it is interacting with
### Steps to reproduce:
1. Download Dependency Walker from [this website](https://www.dependencywalker.com/);
2. Unzip the downloaded depends22_x64.zip, and then run the depends.exe in it;
3. Press Ctrl +O to open an .exe executable.

### Actual behavior:
NVDA crashes and quits after being silent for a while

Here is the error log snippet:
ERROR - watchdog._watcher (17:28:48.876) - watchdog (1728):
Core frozen in stack!
INFO - watchdog._watcher (17:28:48.895) - watchdog (1728):
Listing stacks for Python threads:
Python stack for thread 7472 (nvwave.playWaveFile(error.wav)):

Below is the full error log:
[nvda-old.log](https://github.com/nvaccess/nvda/files/8055280/nvda-old.log)

### Expected behavior:
NVDA works fine

#### NVDA installed/portable/running from source:
installed and portable
#### NVDA version:
2021.3.1 and latest alpha

#### Windows version:
Windows 10 21H2 (x64) build 19044.1526

#### Name and version of other software in use when reproducing the issue:
depends 2.2

#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### LINKED ISSUE #14746: nvdaHelperLocal dll import table hook for oleacc SendMessageTimeoutW not being used
### Steps to reproduce:
1. Press Windows+r to open the Run dialog.
2. Type `\\1.2.3.4` and press enter.
3. NVDA will stop responding because Explorer stops responding. Press alt+tab to switch apps.

### Actual behavior:
NVDA freezes until Explorer responds again.

### Expected behavior:
NVDA shouldn't freeze; watchdog should kill the unresponsive call when you alt+tab.

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
alpha-27892,42dbabcc

#### Windows version:
Windows 11 Version 22H2 (OS Build 22621.1413)
Also reproduced on Windows 11 Version 21H2 (OS Build 22000.1696)

#### Relevant NVDA log snippet

```
ERROR - watchdog._watcher (08:56:19.048) - watchdog (21904):
Core frozen in stack!
INFO - watchdog._watcher (08:56:19.051) - watchdog (21904):
Listing stacks for Python threads:
...
Python stack for thread 13448 (MainThread):
  File "nvda.pyw", line 390, in <module>
  File "core.pyc", line 776, in main
  File "wx\core.pyc", line 2237, in MainLoop
  File "gui\__init__.pyc", line 760, in Notify
  File "core.pyc", line 738, in run
  File "queueHandler.pyc", line 88, in pumpAll
  File "queueHandler.pyc", line 55, in flushQueue
  File "scriptHandler.pyc", line 170, in _queueScriptCallback
  File "keyboardHandler.pyc", line 531, in executeScript
  File "inputCore.pyc", line 199, in executeScript
  File "scriptHandler.pyc", line 216, in executeScript
  File "editableText.pyc", line 187, in script_caret_newLine
  File "editableText.pyc", line 86, in _hasCaretMoved
  File "api.pyc", line 368, in processPendingEvents
  File "IAccessibleHandler\__init__.pyc", line 1075, in pumpAll
  File "IAccessibleHandler\__init__.pyc", line 724, in processFocusWinEvent
  File "IAccessibleHandler\__init__.pyc", line 576, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 64, in getNVDAObjectFromEvent
  File "IAccessibleHandler\__init__.pyc", line 349, in accessibleObjectFromEvent
  File "oleacc.pyc", line 265, in AccessibleObjectFromEvent
```

#### WinDBG stack for main thread
```
0:018:x86> ~0 kpn
 # ChildEBP RetAddr
00 00cfd814 7614d892 win32u!NtUserMessageCall+0xc
01 00cfd85c 76190a21 USER32!SendMessageTimeoutWorker+0xc2
02 00cfd87c 6f1291d2 USER32!SendMessageTimeoutW+0x21
03 00cfd8b8 6f129082 OLEACC!NativeIAccessibleFromWindow+0x70
04 00cfd8e8 6f150972 OLEACC!AccessibleObjectFromWindow+0x27
05 00cfd924 6f150f97 OLEACC!AccessibleObjectFromEvent+0x5e
06 00cfd938 706ce7ba OLEACC!EXTERNAL_AccessibleObjectFromEvent+0x27
WARNING: Stack unwind information not available. Following frames may be wrong.
07 00cfd958 706cd10b _ctypes!DllCanUnloadNow+0x628a
08 00cfd994 706c926f _ctypes!DllCanUnloadNow+0x4bdb
09 00cfda54 706c9a5e _ctypes!DllCanUnloadNow+0xd3f
0a 00cfdb54 706c59a1 _ctypes!DllCanUnloadNow+0x152e
0b 00cfdba4 702d817b _ctypes+0x59a1
0c 00cfdbc8 703735be python37!PyObject_FastCallKeywords+0x15b
...
```

#### Analysis
We're calling AccessibleObjectFromEvent. That calls SendMessageTimeoutW (frame 2). However, NVDA installs a dll import table hook in oleacc for SendMessageTimeoutW:
`oleaccHooks->requestFunctionHook("USER32.dll", "SendMessageTimeoutW", fake_SendMessageTimeoutW);`
We don't see fake_SendMessageTimeoutW nor cancellableSendMessageTimeout in the stack! We should see this between frames 2 and 3.
This suggests that these hooks aren't working for some reason. That's pretty concerning, since watchdog depends on these to keep NVDA responsive in quite a few cases.

CC @michaelDCurran.

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Fixes #14746
Fixes #13335
Partially replaces 7366dee2aab38f1adb7f63b05bd8a1cd3e9ea855

### Summary of the issue:
NVDA doesn't recover when a call to oleacc.AccessibleObjectFromEvent. takes a long time. It instead freezes until the call completes, and the watchdog doesn't cancel it.
See technical discussion in #14746. In short, oleacc and UIAutomationCore don't call SendMessageW and SendMessageTimeoutW in user32 directly so we can't hook the import table of these libraries.

### Description of user facing changes
The str in #14746 should no longer be reproducible.

### Description of development approach
Import table hooks have been changed to use detours. It was actually pretty trivial to do this. As a bonus, I moved the clipboard hook from the remote to the local library as suggested by @jcsteh 

I left the import table hooking mechanism in place, though it is not used by core, it is still available to add-ons.

### Testing strategy:
- [x] Thest str in #14746
- [x] Ensure that NVDA on secure desktop can't access the clipboard
- [x] Overall stability testing

### Known issues with pull request:
As noted by @jcsteh: in https://github.com/nvaccess/nvda/issues/14746#issuecomment-1486480837

> Hooking SendMessage and friends is a bit risky, ... when you use Detours, the function gets hooked for all code in the process.

Therefore this needs extensive testing. And an early merge in a dev cycle. I would really love it if we could have this in 2023.2 but would agree if it was delayed to 2023.3 to give it a longer incubation time.

### Change log entries:
Bug fixes
- NVDA again recovers from many more situations such as applications that stop responding which previously caused it to freeze completely. (#1408, #13335, #14746, #14759)

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

File: nvdaHelper/remote/injection.cpp [hunk 1]
```diff
@@ -341,8 +328,7 @@ BOOL outprocInitialized=FALSE;
  * Initializes the out-of-process code for NVDAHelper 
  * @param secureMode 1 specifies that NVDA is running in seucre mode, 0 says not.
```
Comment (lukaszgo1) [inline nvdaHelper/remote/injection.cpp:329]: Since `injection_initialize` no longer accepts `secureMode` as an argument this part of the documentation comment should be removed.

**Review by jcsteh — COMMENTED** [review]
Thanks for working on this. Looks pretty good to me.

File: nvdaHelper/local/nvdaHelperLocal.cpp [hunk 2]
```diff
@@ -19,13 +19,21 @@ This license can be found at:
...
 
-DllImportTableHooks* oleaccHooks = NULL;
-DllImportTableHooks* uiaCoreHooks = NULL;
+typedef LRESULT(WINAPI *SendMessageW__funcType)(HWND, UINT, WPARAM, LPARAM);
+typedef LRESULT(WINAPI *SendMessageTimeoutW_funcType)(HWND, UINT, WPARAM, LPARAM, UINT, UINT, PDWORD_PTR);
+typedef BOOL(WINAPI *OpenClipboard_funcType)(HWND);
+
+SendMessageW__funcType real_SendMessageW = nullptr;
+SendMessageTimeoutW_funcType real_SendMessageTimeoutW = nullptr;
+OpenClipboard_funcType real_OpenClipboard = nullptr;
```
[the remark this answers is not in the document]
Comment (leonardder) [reply nvdaHelper/local/nvdaHelperLocal.cpp:34]: Ah, you need to give decltype a reference to the function. That works!

**Comment by amirsol81** [comment]
I've been trialing the test build over the last hour or so, and the results are hugely positive. With this test build NVDA no longer gets silent or unresponsive when an Explorer crash occurs or if a program gets too long to load/respond. In fact, I've never been able to force it to become silent or unresponsive intentionally. Of course, the actual results with an Alpha release loaded with add-ons might or might not be different, but the Pull Request is apparently quite beneficial. Looking forward to testing it as part of an upcoming alpha release.

**Comment by cary-rowen** [comment]
Hi @leonardder ,
Does that fix work for #13335 as well.

**Comment by leonardder** [comment]
Would you be able to test that with a [try build](https://ci.appveyor.com/api/buildjobs/hsflmcd3p7rgy907/artifacts/output/nvda_snapshot_pr14759-27983,4415eb7d.exe)?

**Comment by seanbudd** [comment]
A try build is building now: https://ci.appveyor.com/project/NVAccess/nvda/builds/46680365/artifacts

**Comment by cary-rowen** [comment]
@leonardder 
Yes, I tested #13335 with the latest try build and this PR fixes it.
This is really exciting, thanks!

File: nvdaHelper/local/nvdaHelperLocal.cpp [hunk 3]
```diff
@@ -19,21 +19,25 @@ This license can be found at:
...
 #include "dllImportTableHooks.h"
 #include "rpcsrv.h"
 
-DllImportTableHooks* oleaccHooks = NULL;
-DllImportTableHooks* uiaCoreHooks = NULL;
+decltype(&SendMessageW) real_SendMessageW = nullptr;
+decltype(&SendMessageTimeoutW) real_SendMessageTimeoutW = nullptr;
+decltype(&OpenClipboard) real_OpenClipboard = nullptr;
+
+bool isSecureModeNVDAProcess=false;
```
Comment (jcsteh) [inline nvdaHelper/local/nvdaHelperLocal.cpp:32]: nit: Do we really need this global? I don't think anything uses it outside of nvdaHelperLocal_initialize.

Comment (leonardder) [reply nvdaHelper/local/nvdaHelperLocal.cpp:32]: Indeed, we might as well remove it. I copied it from remote and didn't realise that explicit deinit of hooks is not necessary.

**Review by michaelDCurran — APPROVED** [review]
Looks all good to me :)
