### PR TITLE
WasapiPlayer: Call IAudioClient::Reset in completeStop() rather than in stop().

### LINKED ISSUE #18101: Remote: Sometimes no speech from UAC screen on remote computer
### Steps to reproduce:
1. In NVDA menu -> Preferences -> Settings -> Remote, set up a remote computer as follows:
    - Enable remote access: checked
    - Automatically connect after NVDA starts: checked
    - Mode: Allow this computer to be controlld
    - Server: Host locally
    - Key: [some key of your choosing]
2. On the remote computer, in NVDA menu -> Preferences -> Settings -> General, press: Use currently saved settings during sign-in and on secure screens (requires administrator privileges).
3. On your local computer, use NVDA remote access to connect to the remote computer you set up in (1).
4. Switch to the remote computer.
5. Press Windows+r, type cmd, and press control+shift+enter to bring up a UAC screen.

### Actual behavior:
Sometimes, but not always, nothing is spoken on the local computer. The remote computer speaks, but the local computer does not. However, keys pressed on the local computer behave as expected.

### Expected behavior:
Speech from the UAC screen on the remote computer should be heard on the local computer.

### NVDA logs, crash dumps and other attachments:
This is a bit tricky because of the involvement of the secure desktop. Let me know what information would be most helpful here. Otherwise, I'll try to get logs from all three places, but this might take me some time.

#### NVDA installed/portable/running from source:
Installed on both.

#### NVDA version:
Version: alpha-36403,558905f5 (2025.2.0.36403)

#### Windows version:
Version 24H2 (OS Build 26100.4061)

#### Does the issue still occur after restarting your computer?
Yes.

### PR DESCRIPTION
**Pull request by jcsteh**
### Link to issue number:
Fixes #18101
May address #17131, though I'm not sure and I think there's still a thread safety bug in that third party synth driver even if it does.

### Summary of the issue:
Sometimes, speech is silent on the local computer when using NVDA Remote Access and a UAC screen appears on the remote computer. This occurs because NVDA tries to play a sound, which calls WavePlayer.stop, which throws an AUDCLNT_E_BUFFER_OPERATION_PENDING exception. That exception isn't caught, so it prevents speech handlers from being registered.

### Description of user facing changes:
When using NVDA Remote Access, speech from User Account Control screens on the remote computer now works reliably.

### Description of development approach:
AUDCLNT_E_BUFFER_OPERATION_PENDING is being returned from IAudioClient::Reset() called by WasapiPlayer::stop(). Per [the documentation](https://learn.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudioclient-reset#return-value), Reset can return AUDCLNT_E_BUFFER_OPERATION_PENDING if "The client is currently writing to or reading from the buffer."

It's indeed slightly possible that the feeder thread is still in WasapiPlayer::feed() when we call WasapiPlayer::stop() on the main thread. This is why stopping is split into two phases: the stop() call itself, generally called on the main thread, and completeStop(), called by the feeder thread when it sees that stop() has been called.

Thus, we fix this problem by moving the IAudioClient::Reset() call from WasapiPlayer::stop() to WasapiPlayer::completeStop(), ensuring that it is called on the feeder thread and therefore not while the buffer is being written to. Audio still stops immediately when WasapiPlayer::stop() is called due to the call to IAudioClient::Stop(), which does not care about whether another thread is writing to the buffer.

We also call IAudioClient::Stop() before setting playState. Otherwise, the feeder thread might see the playState change and call client->Reset() before client->Stop() runs, causing AUDCLNT_E_NOT_STOPPED.

### Testing strategy:
Followed steps in #18101. Verified the expected result 30 times.

### Known issues with pull request:
None.

### Code Review Checklist:
- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

@coderabbitai summary

### CODE REVIEW

File: nvdaHelper/local/wasapi.cpp [hunk 1]
```diff
@@ -610,6 +606,12 @@ HRESULT WasapiPlayer::stop() {
 }
 
 void WasapiPlayer::completeStop() {
+	HRESULT hr = client->Reset();
+	if (FAILED(hr)) {
+		LOG_ERROR(L"Couldn't reset stream: " << hr);
```
Comment (jcsteh) [inline nvdaHelper/local/wasapi.cpp]: We may want to make this `LOG_DEBUGWARNING` eventually if this is regularly caused by audio devices being unplugged or whatever. However, I think it makes sense for it to be ERROR at least initially so we don't swallow/understate what might turn out to be real problems.

Comment (michaelDCurran) [reply nvdaHelper/local/wasapi.cpp]: Having this as LOG_ERROR for me causes some kind of freeze / deadlock when the original bug occurs. Here is a fragment of my log of the secure copy as  it connects:
```
INFO - _remoteClient.session.RemoteSession.handleClientConnected (07:40:14.275) - MainThread (20852):
Client connected: {'id': 62, 'connection_type': 'master'}
INFO - watchdog.waitForFreezeRecovery (07:40:14.777) - watchdog (17848):
Starting freeze recovery after 0.5002936000018963 seconds.
DEBUGWARNING - watchdog.waitForFreezeRecovery (07:40:14.777) - watchdog (17848):
Listing stacks for Python threads:
Python stack for thread 19936 (nvwave.playWaveFile(controlled.wav)):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "nvwave.pyc", line 128, in play
  File "nvwave.pyc", line 337, in feed
  File "NVDAHelper.pyc", line 323, in nvdaControllerInternal_logMessage
  File "logHandler.pyc", line 262, in _log
  File "logging\__init__.pyc", line 1634, in _log
  File "logging\__init__.pyc", line 1644, in handle
  File "logging\__init__.pyc", line 1706, in callHandlers
  File "logHandler.pyc", line 398, in handle
  File "extensionPoints\__init__.pyc", line 56, in notify
  File "extensionPoints\util.pyc", line 230, in callWithSupportedKwargs
  File "nvwave.pyc", line 566, in playErrorSound
  File "nvwave.pyc", line 112, in playWaveFile
  File "nvwave.pyc", line 387, in stop
  File "nvwave.pyc", line 459, in _setVolumeFromConfig
  File "nvwave.pyc", line 428, in setVolume

Python stack for thread 17848 (watchdog):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "watchdog.pyc", line 163, in _watcher
  File "watchdog.pyc", line 170, in waitForFreezeRecovery
  File "logHandler.pyc", line 64, in getFormattedStacksForAllThreads

Python stack for thread 1124 (queue_thread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "_remoteClient\transport.pyc", line 540, in sendQueue
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 22192 (Thread-4_connector_loop):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "_remoteClient\transport.pyc", line 705, in run
  File "_remoteClient\transport.pyc", line 352, in run
  File "_remoteClient\transport.pyc", line 390, in _readLoop

Python stack for thread 1604 (winInputHook):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "winInputHook.pyc", line 108, in hookThreadFunc

Python stack for thread 16096 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "UIAHandler\__init__.pyc", line 554, in MTAThreadFunc
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 2420 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 207, in run
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 21160 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 264, in run

Python stack for thread 2132 (ScheduleThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "utils\schedule.pyc", line 90, in run

Python stack for thread 20852 (MainThread):
  File "nvda.pyw", line 309, in <module>
  File "core.pyc", line 1049, in main
  File "wx\core.pyc", line 2262, in MainLoop
  File "wx\core.pyc", line 3427, in <lambda>
  File "extensionPoints\__init__.pyc", line 56, in notify
  File "extensionPoints\util.pyc", line 230, in callWithSupportedKwargs
  File "_remoteClient\session.pyc", line 376, in handleChannelJoined
  File "_remoteClient\session.pyc", line 359, in handleClientConnected
  File "_remoteClient\session.pyc", line 224, in handleClientConnected
  File "_remoteClient\cues.pyc", line 77, in clientConnected
  File "_remoteClient\cues.pyc", line 57, in _playCue
  File "nvwave.pyc", line 112, in playWaveFile
  File "nvwave.pyc", line 387, in stop
```

Comment (michaelDCurran) [reply nvdaHelper/local/wasapi.cpp]: Note that I hear the start of the connection sound and then it is cut off. And then just silence. No speech on either machine.

Comment (jcsteh) [reply nvdaHelper/local/wasapi.cpp]: Hmm. I guess error isn't ideal precisely because it plays a sound and we're potentially dealing with an error playing a sound. That said, you ideally shouldn't be hitting this error any more at all, so that's a bit worrying. Can you try with LOG_DEBUGWARNING instead? I'd like to know what the error code is; i.e. whether it's still AUDCLNT_E_BUFFER_OPERATION_PENDING or something else.

**Comment by michaelDCurran** [comment]
From a user point of view, the try build with LOG_DEBUGWARNING is working fine. Even when reset fails.
On the remote machine I here:
* The connection sound
* The connection message
* The user account control dialog
On the local machine, I here:
* The user account control dialog.

Here is a log fragment showing the reset error:
```
INFO - _remoteClient.client.onConnectedAsFollower (13:35:36.021) - MainThread (21220):
Control connector connected
INFO - _remoteClient.session.RemoteSession.handleClientConnected (13:35:36.032) - MainThread (21220):
Client connected: {'id': 34, 'connection_type': 'master'}
DEBUGWARNING - NVDAHelperLocal (13:35:36.032) - nvwave.playWaveFile(controlled.wav) (20456):
Thread 20456, build\x86\local\wasapi.cpp, WasapiPlayer::completeStop, 613:
Couldn't reset stream: -2004287483
```
Error 0x88890005 | AUDCLNT_E_NOT_STOPPED

**Comment by SaschaCowley** [comment]
@michaelDCurran I think what is happening is that on one thread, `playState` is being set to `PlayState::stopping` **then** `IAudioClient::Stop` is being called, but on the background thread, `feed` is being called before the `IAudioClient::Stop` call completes, so `IAudioClient::Reset` is happening **before** ``Stop`. @jcsteh is there a reason we set `playState` to `stopping` **before** we call `IAudioClient::Stop`?

**Comment by jcsteh** [comment]
Nah, just my incompetence. Sorry. I'll fix it.

**Comment by SaschaCowley** [comment]
Please don't beat yourself up. It does no-one any good.

**Comment by jcsteh** [comment]
Thread safety is such fun, innit?

**Comment by jcsteh** [comment]
I'll push another try build and verify this still fixes the remote problem just in case. If so, we can mark this as ready for review.

**Comment by SaschaCowley** [comment]
@jcsteh or @michaelDCurran have you had a chance to test the latest try build yet? I have been unable to reduce the bug regardless of NVDA version

File: nvdaHelper/local/wasapi.cpp [hunk 2]
```diff
@@ -586,22 +587,21 @@ bool WasapiPlayer::didPreferredDeviceBecomeAvailable() {
 }
 
 HRESULT WasapiPlayer::stop() {
-	playState = PlayState::stopping;
 	HRESULT hr = client->Stop();
+	// It's important that we set playState *after*
+	// calling client->Stop() because otherwise, the feeder thread might see the
+	// playState change and call client->Reset() before client->Stop() runs,
+	// causing AUDCLNT_E_NOT_STOPPED.
+	playState = PlayState::stopping;
```
Comment (SaschaCowley) [inline nvdaHelper/local/wasapi.cpp:595]: Shouldn't we move this to after the failure check? Otherwise if calling `client->Stop` fails, we'll still set `playState` to `stopping` and `client->Reset` will be called even though `player` won't be stopped?

Comment (jcsteh) [reply nvdaHelper/local/wasapi.cpp:595]: You're correct that this might result in Reset being called when Stop hasn't been. However, I think the alternative is worse: we wouldn't clean up our state even though the caller asked us to stop. Also, most of the time, a failure to stop is probably (admittedly speculative) because of some device failure, which means audio has likely already stopped one way or another.

**Comment by jcsteh** [comment]
I tested the latest build and can no longer reproduce the remote problem. I'll mark this as ready for review.

**Comment by michaelDCurran** [comment]
I've been running the latest try build remotely for quite some time, successfully bringing up UAC dialogs remotely with out issue. I think it is good to go.

File: nvdaHelper/local/wasapi.cpp (hunk 2 above)
Comment (SaschaCowley) [reply nvdaHelper/local/wasapi.cpp:595]: That sounds reasonable. Thanks for the explanation.

**Review by SaschaCowley — APPROVED** [review]
Thanks, @jcsteh
