### PR TITLE
Report the presence of multiple annotations

### LINKED ISSUE #14360: Don't fall back to IA2 nRelations and friends if relationTargetsOfType succeeds but returns no targets
In #13112, `NVDAObjects.IAccessible.IAccessible._getIA2TargetsForRelationsOfType` gained support for IAccessible2_2::relationTargetsOfType to make retrieval of relations faster. However, this code [currently falls back to IAccessible2::nRelations and friends](https://github.com/nvaccess/nvda/blob/9329591bc8517470a7f70ebba9fa807a8478e5b5/source/NVDAObjects/IAccessible/__init__.py#L1581) if there were no targets retrieved, even if relationTargetsOfType was successful. nRelations and friends can be slow because the server potentially has to calculate relations the client doesn't even want.

I think `_getIA2TargetsForRelationsOfType` should only fall back to the old method if relationTargetsOfType fails or is not supported. Currently, [a warning is logged if this happens, but the code doesn't early return](https://github.com/nvaccess/nvda/blob/9329591bc8517470a7f70ebba9fa807a8478e5b5/source/NVDAObjects/IAccessible/__init__.py#L1579). If it succeeds, 0 targets is a valid return and should not result in a fallback.

I discovered this because we currently have a case in Firefox where calculation of a particular relation is a bit slow in large documents. It turns out that this particular relation isn't even supported by IA2, so I'm going to [fix that](https://bugzilla.mozilla.org/show_bug.cgi?id=1800048), which will eliminate the user impact of this issue. Thus, I can't provide decent steps to reproduce here because the document is huge, which means you need to be using the new accessibility cache which isn't yet enabled by default, and because by the time anyone gets to this, the performance problem will probably no longer be observable due to my fix. Nevertheless, I think it's probably worth fixing this eventually for general performance.

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Stacked against #14480 
Supersedes #14426

### Summary of the issue:
Currently, NVDA only announces the first annotation target, and only announces the first annotation summary. 

#14480 introduces the ability to cycle through multiple annotations targets.
This PR introduces announcing the presence of multiple annotation targets.

When multiple annotation targets are present with different roles, NVDA should announce them.
Example:
- A footnote, a comment, and a no-role annotation are present
- NVDA should announce "has footnote, has comment, has details" to make it easier for the user to find the annotation they want to interact with.

### Description of user facing changes
When the annotation feature is enabled, NVDA will now report all the unique annotation target roles.

### Description of development approach
- From the virtual buffer, exposed comma separated values for the roles of annotation targets via the "detailsRoles" property.
- Converted all aria-details functions to plural form (handling a collection rather than a single optional value).
- Removed usages of, and deprecated `nvdaObject.hasDetails`, `nvdaObject.detailsSummary`, `nvdaObject.detailsRole`
   - These are replaced with new Annotations types

### Testing strategy:
- [x] Manual testing on Chrome and Firefox with: https://codepen.io/reefturner/pen/poKLQyj
- [x] System tests have been added for the presence and reporting of multiple annotations

### Known issues with pull request:
It appears that an internally documented chrome bug has not been reported to Chromium/Google yet.

### Change log entries:
New features
```
- The presence of multiple annotations are now reported.
For example, when text has a comment and a footnote associated with it.
```

For Developers
```
- ``NVDAObject.hasDetails``, ``NVDAObject.detailsSummary``, ``NVDAObject.detailsRole`` has been deprecated, instead use ``NVDAObject.annotations``.
```

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

File: nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp [hunk 1]
```diff
@@ -47,43 +48,73 @@ bool hasXmlRoleAttribContainingValue(const map<wstring,wstring>& attribsMap, con
...
+		min<size_t>(
+			numRelations.value_or(FETCH_ALL),  // Default is to fetch all relations.
+			static_cast<size_t>((numeric_limits<long>::max)())
+		)
+	);
+
+	const bool isChrome = this->toolkitName.compare(L"Chrome") == 0;
+	if (isChrome) {
+		// A bug in Chrome causes a buffer overrun if numRelations is less than the total number of targets the node has.
+		// TODO: has this been reported?
```
Comment (seanbudd) [inline nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp:67]: is it worth testing, confirming and reporting this bug to Chromium? I don't think we have yet.

Comment (michaelDCurran) [reply nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp:67]: It was reported to Chromium in https://bugs.chromium.org/p/chromium/issues/detail?id=1399184
However, the bug only states that Chromium ignores numRelations and gives back all available. It does not mention any buffer overrun. If there is in deed an overrun, it would be within Chromium, as chromium is the one that allocates the buffer.
Either way though, the general issue has been reported and Google will no doubt look into it.
Our work around is sufficient here.

**Comment by michaelDCurran** [comment]
This pr looks all good, except for the changes to braille.py. This is very large, and I am struggling to follow what was necessary to change verses a whole bunch of refactoring. Would it be at all possible to drop the refactoring from this pr and only include the ncessary changes to braille.py? If this is not possible and or if there is good reason and @seanbudd  knows this history, then I'm put in a bit more effort to try and get through that particular file diff.

**Comment by seanbudd** [comment]
@michaelDCurran I've slightly amended `braille.py`. It should now be much easier to review when hiding whitespace changes.
If it is still cumbersome, let me know, and I will move the refactor out of this PR.

**Review by michaelDCurran — APPROVED** [review]

**Review by michaelDCurran — APPROVED** [review]
