### PR TITLE
Restore new live region announcement implementation for mshtml

### LINKED ISSUE #11834: `ui.browseableMessage()` broken since alpha-21356,ae4ea8f9
### Steps to reproduce:
1. Open the NVDA Python console (default: NVDA+CTRL+z).
2. Execute the following instructions:
   `import ui;ui.browseableMessage("This is a test!", "Test")`

### Actual behavior:
NVDA crashes with the following in the log:

```
CRITICAL - watchdog._crashHandler (07:43:28.223) - Dummy-5 (12140):
NVDA crashed! Minidump written to C:\Users\andre\AppData\Local\Temp\nvda.log\..\nvda_crash.dmp
INFO - watchdog._crashHandler (07:43:30.437) - Dummy-5 (12140):
Listing stacks for Python threads:
Python stack for thread 12140 (Dummy-5):
  File "watchdog.pyc", line 213, in _crashHandler
  File "watchdog.pyc", line 63, in getFormattedStacksForAllThreads

Python stack for thread 4144 (virtualBuffers.MSHTML.VirtualBuffer.loadBuffer):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "virtualBuffers\__init__.pyc", line 444, in _loadBuffer

Python stack for thread 10748 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x05BCACD8>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 332, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 12044 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 120, in _watcher

Python stack for thread 10612 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 79, in hookThreadFunc

Python stack for thread 7352 (_UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "_UIAHandler.pyc", line 315, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 3700 (braille._BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "braille.pyc", line 2187, in func

Python stack for thread 13092 (MainThread):
  File "nvda.pyw", line 247, in <module>
  File "core.pyc", line 568, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1062, in Notify
  File "core.pyc", line 538, in run
  File "queueHandler.pyc", line 88, in pumpAll
  File "queueHandler.pyc", line 55, in flushQueue
  File "eventHandler.pyc", line 65, in _queueEventCallback
  File "eventHandler.pyc", line 241, in executeEvent
  File "eventHandler.pyc", line 284, in doPreGainFocus
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1121, in event_focusEntered
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 517, in getObjectSpeech
  File "speech\__init__.pyc", line 381, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 762, in _get_name
  File "comtypes\__init__.pyc", line 857, in __call__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

INFO - watchdog._crashHandler (07:43:30.438) - Dummy-5 (12140):
Restarting due to crash
```

### Expected behavior:
No crash.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-21359,aecff99a

#### Windows version:
10 Insider (64-bit) build 20251.1

#### Name and version of other software in use when reproducing the issue:
Reproducible with NVDA+f when quickly pressed two times in Word, Firefox, etc. And in a lot of other situations.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Bug introduced in a recent alpha build.

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Reverts #11838
Fixes #11834

### Summary of the issue:
#11838 reverted #9079 that causes a crash in mshtml documents, reproducible when pressing NVDA+F twice to open formatting info in a browseable message. I was able to pinpoint it to a needless setting of live politeness to nullptr instead of an empty string, which is the default when politeness is not set, based on the behavior of the default constructor of wstring.

### Description of how this pull request fixes the issue:
Fixed the issue.  Also optimized some code while at it.

### Testing performed:
Opening a browseable message by pressing NVDA+F twice in a document.

### Known issues with pull request:
None known

### Change log entry:
In pr
Secti

### CODE REVIEW

File: nvdaHelper/vbufBackends/mshtml/node.cpp [hunk 1]
```diff
@@ -384,36 +407,35 @@ void MshtmlVBufStorage_controlFieldNode_t::preProcessLiveRegion(const MshtmlVBuf
...
 }
 
-void MshtmlVBufStorage_controlFieldNode_t::reportLiveText(wstring& text) {
-	for(auto c: text) {
-		if(!iswspace(c)) {
-			nvdaController_speakText(text.c_str());
-			break;
-		}
+void MshtmlVBufStorage_controlFieldNode_t::reportLiveText(wstring& text, wstring& politeness) {
+	if(!all_of(text.cbegin(), text.cend(), iswspace)) {
```
Comment (leonardder) [inline nvdaHelper/vbufBackends/mshtml/node.cpp:414]: note, all_of returns true for an empty string, which is exactly what we want.

File: nvdaHelper/vbufBackends/mshtml/node.cpp [hunk 2]
```diff
@@ -379,7 +379,7 @@ void MshtmlVBufStorage_controlFieldNode_t::preProcessLiveRegion(const MshtmlVBuf
 		if (this->ariaLiveNode) {
 			this->ariaLivePoliteness = this->ariaLiveNode->ariaLivePoliteness;
 		} else {
-			this->ariaLivePoliteness = nullptr;
+			this->ariaLivePoliteness = L"";
```
Comment (feerrenrut) [inline nvdaHelper/vbufBackends/mshtml/node.cpp:382]: Annoyingly this would have been captured by the visual studio '/analyze' option.

**Review by feerrenrut — APPROVED** [review]
Thanks @leonardder

File: nvdaHelper/vbufBackends/mshtml/node.cpp (hunk 2 above)
Comment (leonardder) [reply nvdaHelper/vbufBackends/mshtml/node.cpp:382]: Is there a reason why we can't use this?

Comment (feerrenrut) [reply nvdaHelper/vbufBackends/mshtml/node.cpp:382]: I think it was because there are too many other problems. We would either need to fix all the existing issues (which are likely false positives), or create a system to filter the noise and only show new issues.
