### PR TITLE
Stop regex_error exception when quick navigating to article landmarks

### LINKED ISSUE #8980: Freeze when navigating by landmarks with certain labeled article landmarks
### Steps to reproduce:

There are several prerequisites:

1. You have to have an account on some Mastodon social network instance.
2. You have to have the Extended ARIA Add-On installed and the Articles landmark activated.

Steps:

1. Log into https://dev.pinafore.social. Pinafore is an alternative web client to the Mastodon social network.
  * If you're not logged in, click the AddInstance link, fill in your instance name, like mastodon.social or toot.cafe, or whichever instance you're on, then click Login.
  * Authorize Pinafore to access your account.
2. After you've logged in, start navigating the Home timeline via the letter D. At some point, NVDA will cause a Windows ascending error tone to be heard, and fall silent. The braille display, if connected, will continue to blink, but NVDA is essentially dead then.
3. Restart NVDA, then simply arrow through the page onto any article. A crash does not occur, NVDA reads the article name normally.

### Actual behavior:

NVDA produces an error sound, then falls silent. As if it partially crashed. Braille continues to blink, but won't respond to anything.

### Expected behavior:

No crash.

#### NVDA Installed/portable/running from source:

Installed.

#### NVDA version:

NVDA version alpha-16298,c651588e

#### Windows version:

Windows 10 19H1 18282 build. But also happens on 1809 regular.

#### Name and version of other software in use when reproducing the issue:

Firefox Nightly 65.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA?

2018.4beta, 2018.3.2, happens with both, too.

#### Developer info for an article element that causes this problem:

INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (15:28:21.299):
Developer info for navigator object:
name: u'Eric Eggert, RT @bigfinish@twitter.comComing September 2019, @BilliePiper is returning to the #DoctorWho universe in Rose Tyler: The Dimension Cannon. -> http://bit.ly/2FIKkiZFour episodes follow Rose\u2019s mission to seek out the Doctor, the only person who can save the doomed multiverse\u2026, 1 hour ago, @yatil@micro.yatil.net, Unlisted'
role: ROLE_DOCUMENT
states: STATE_READONLY, STATE_FOCUSABLE
isFocusable: True
hasFocus: False
Python object: <baseObject.Dynamic_BrokenFocusedStateDocumentMozillaIAccessible object at 0x05B715F0>
Python class mro: (<class 'baseObject.Dynamic_BrokenFocusedStateDocumentMozillaIAccessible'>, <class 'NVDAObjects.IAccessible.mozilla.BrokenFocusedState'>, <class 'NVDAObjects.IAccessible.mozilla.Document'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Document'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: RectLTWH(left=665, top=1398, width=900, height=1013)
value: None
appModule: <'firefox' (appName u'firefox', process ID 2012) at address 5766fb0>
appModule.productName: u'Firefox Nightly'
appModule.productVersion: u'65.0a1'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 590326L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 14052
windowText: u'toot.cafe \xb7 Home - Firefox Nightly'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0xc0e57b4 at 5a2b8f0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=590326L, objectID=-4, childID=-67109111
IAccessible accName: u'Eric Eggert, RT @bigfinish@twitter.comComing September 2019, @BilliePiper is returning to the #DoctorWho universe in Rose Tyler: The Dimension Cannon. -> http://bit.ly/2FIKkiZFour episodes follow Rose\u2019s mission to seek out the Doctor, the only person' (truncated)
IAccessible accRole: ROLE_SYSTEM_DOCUMENT
IAccessible accState: STATE_SYSTEM_READONLY, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048640)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 590326
IAccessible2 uniqueID: -67109111
IAccessible2 role: ROLE_SYSTEM_DOCUMENT
IAccessible2 states: IA2_STATE_SELECTABLE_TEXT, IA2_STATE_OPAQUE (5120)
IAccessible2 attributes: u'margin-left:0px;text-align:start;text-indent:0px;setsize:20;container-busy:false;margin-right:0px;tag:article;class:status-article status-in-timeline;margin-top:0px;posinset:6;margin-bottom:0px;xml-roles:article;display:grid;explicit-name:true;'

#### End of nvda.log from pressing D before such a crash onwards

Input: kb(laptop):d
DEBUGWARNING - watchdog._watcher (15:24:05.726):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 217, in <module>
  File "core.pyc", line 515, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 963, in Notify
  File "core.pyc", line 486, in run
  File "queueHandler.pyc", line 86, in pumpAll
  File "queueHandler.pyc", line 53, in flushQueue
  File "scriptHandler.pyc", line 145, in _queueScriptCallback
  File "scriptHandler.pyc", line 187, in executeScript
  File "browseMode.pyc", line 414, in <lambda>
  File "browseMode.pyc", line 386, in _quickNavScript
  File "virtualBuffers\__init__.pyc", line 570, in _iterNodesByAttribs

DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:10.657):
Unhandled extended packet of type 'U': 'U\x05'
DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:10.709):
Unhandled extended packet of type 'U': 'U\xff'
DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:10.759):
Unhandled extended packet of type 'U': 'U\x06'
DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:10.809):
Unhandled extended packet of type 'U': 'U\xff'
DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:10.907):
Unhandled extended packet of type 'U': 'U\x08'
DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:11.061):
Unhandled extended packet of type 'U': 'U\xff'
DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:11.161):
Unhandled extended packet of type 'U': 'U\n'
DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:11.260):
Unhandled extended packet of type 'U': 'U\x0b'
DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:11.311):
Unhandled extended packet of type 'U': 'U\xff'
DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:11.460):
Unhandled extended packet of type 'U': 'U\r'
DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:11.559):
Unhandled extended packet of type 'U': 'U\xff'
WARNING - watchdog._watcher (15:24:20.730):
Core frozen in stack:
  File "nvda.pyw", line 217, in <module>
  File "core.pyc", line 515, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 963, in Notify
  File "core.pyc", line 486, in run
  File "queueHandler.pyc", line 86, in pumpAll
  File "queueHandler.pyc", line 53, in flushQueue
  File "scriptHandler.pyc", line 145, in _queueScriptCallback
  File "scriptHandler.pyc", line 187, in executeScript
  File "browseMode.pyc", line 414, in <lambda>
  File "browseMode.pyc", line 386, in _quickNavScript
  File "virtualBuffers\__init__.pyc", line 570, in _iterNodesByAttribs

DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:35.359):
Unhandled extended packet of type 'U': 'U\x01'
DEBUGWARNING - brailleDisplayDrivers.handyTech.BrailleDisplayDriver._handleInputStream (15:24:35.411):
Unhandled extended packet of type 'U': 'U\xff'
WARNING - watchdog._watcher (15:24:35.740):
Core frozen in stack:
  File "nvda.pyw", line 217, in <module>
  File "core.pyc", line 515, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 963, in Notify
  File "core.pyc", line 486, in run
  File "queueHandler.pyc", line 86, in pumpAll
  File "queueHandler.pyc", line 53, in flushQueue
  File "scriptHandler.pyc", line 145, in _queueScriptCallback
  File "scriptHandler.pyc", line 187, in executeScript
  File "browseMode.pyc", line 414, in <lambda>
  File "browseMode.pyc", line 386, in _quickNavScript
  File "virtualBuffers\__init__.pyc", line 570, in _iterNodesByAttribs

### Other info

The pull request that will introduce these new names for the article elements into Pinafore is [here](https://github.com/nolanlawson/pinafore/pull/690).

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
Fixes #8980 

### Summary of the issue:
NvDA's browseMode quick navigation in virtualBuffers uses regular expressions to match on a node's attributes to locate the next valid item.
However, in certain scenarios, Firefox can seem to freeze when quick navigating by landmarks, if the extendedAria add-on in installed and reportArticles is enabled.
Technically:
In Firefox at least, it seems that the c++ regex_match function can throw a regex_error exception if the input string is too long. For instance, if searching for landmarks (including articles) and it comes upon an article node with an aria-label with a length greater than 294 characters.
 
### Description of how this pull request fixes the issue:
1. We now catch regex_error thrown by regex_match, log a debug warning, and return false (I.e. pretend the regex did not match). This in itself stops the freeze, but does mean that a possible article will be skipped.
2. We limit the  length of attribute value strings added to re regular expression input to 100 characters.  Currently this is for all attribute values, as matchAttributes is really supposed to be agnostic to what attributes it is dealing with. Though we could specifically hardcode a check for 'name'. I can't however really think of a situation where any attribute value needs to be more than 100 characters for matching purposes. We could instead also up the limit to say 256, or in deed 294, but I have a feeling this may not be universal across machines.

### Testing performed:
Tested the original testcases in #8980. The correct articles were found, and no freeze occured.

### Known issues with pull request:
None.

### Change log entry:
Bug fixes:
* Fixed a freeze in Firefox sometimes seen when qquick navigating by landmarks, if the extendedAria add-on is in use. (#8980)

### CODE REVIEW

File: nvdaHelper/vbufBase/storage.cpp [hunk 1]
```diff
@@ -132,10 +136,20 @@ inline void outputEscapedAttribute(wostringstream& out, const wstring& text) {
 			default:
 			out << *it;
 		}
+		if(maxLength>0) {
+			count++;
+			if(count==maxLength) {
+				break;
```
Comment (jcsteh) [inline nvdaHelper/vbufBase/storage.cpp]: Is it worth logging a debugWarning when we truncate? This shouldn't happen too often and it's possible this might be useful when trying to debug some future (as yet unknown) issue.

**Review by jcsteh — APPROVED** [review]

File: nvdaHelper/vbufBase/storage.cpp (hunk 1 above)
Comment (michaelDCurran) [reply nvdaHelper/vbufBase/storage.cpp]: Agreed.  outputEscapedAttribute now returns the number of input characters outputted to the stream. matchattributes checks this length against the original string length and logs a debug warning with the name of the attribute if the length is truncated.

File: nvdaHelper/vbufBase/storage.cpp [hunk 2]
```diff
@@ -122,7 +122,12 @@ VBufStorage_fieldNode_t* VBufStorage_fieldNode_t::nextNodeInTree(int direction,
 	return tempNode;
 }
 
-inline void outputEscapedAttribute(wostringstream& out, const wstring& text) {
+// @param out the stream to which the escaped attribute string should be written
+// @param text The attribute string to be escaped
+// @param maxLength the maximum length of the attribute string that should be copied. If maxLength is 0 or not specified, the entire string is copied.
+// @return the number of characters written to the output stream (before expantion / filtering). This number can be used to see if the string was truncated at all.
```
Comment (jcsteh) [inline nvdaHelper/vbufBase/storage.cpp]: nit: expantion -> expansion (s instead of t)

**Review by jcsteh — APPROVED** [review]
It's worth noting that because this count is before expansion, the truncated string might actually be longer than 100 chars. I don't think that really matters, though, and the alternative is more confusing.
