### PR TITLE
Actually terminate (clean up) the Microsoft UIA Abstraction remote operations library on NVDA exit.

### LINKED ISSUE #16072: Portable version of NVDA starts very slowly and is unusable
When I try to start a portable copy of NVDA (I have used many Alpha and Beta versions since December 2023) it may start the first time, but when I exit the program and start it again, NVDA tries to start but this happens very slowly, and finally I have to boot the computer, if I don't manage to kill the NVDA process. Sometimes I can't kill the NVDA process and reboot seems to be the only solution. NVDA doesn't react on key presses and my Braille display (Braillex EL 80c) is empty.

I have never used installed versions of NVDA, and everything has gone correctly until last December when I moved from 32 bit  Windows 7 to 64 bit Windows 11 Pro. I am using the same setting files which I used in Windows 7. I put the portable copy to C:nvda (beta version) and C:\nvda2 (Alpha version) and copied the one userconfig folder to these NVDA folders. Is it possible that my problems have something to do with userconfig folder's content, normal text-based files?
### Steps to reproduce:
Put the portable NVDA to a folder, i.e. C:\nvda, and start and quit it a few times.
### Actual behavior:

NVDA starts very slowly, the speech synthesizer says "Starting NVDA. Please wait..." and nothing happens after this.
### Expected behavior:

NVDA starts normally and it can be used normally.
### NVDA logs, crash dumps and other attachments:
Here are some lines from the nvda.log file? Should I post the whole file? I'm not sure

Initializing MathPlayer
WARNING - mathPres.initialize (08:06:34.408) - MainThread (12452):
MathPlayer 4 not available
DEBUGWARNING - core.main (08:06:34.408) - MainThread (12452):
Slow starting core (10.44 sec)
IO - speech.speech.speak (08:06:34.408) - MainThread (12452):
Speaking ['Loading NVDA. Please wait...']
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (08:06:34.408) - MainThread (12452):
No CLDR data for locale fi_FI
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (08:06:34.408) - MainThread (12452):
No symbol data for locale fi_FI
INFO - core.main (08:06:34.497) - MainThread (12452):
Using wx version 4.2.1 msw (phoenix) wxWidgets 3.2.2.1 with six version 1.16.0
DEBUG - core.main (08:06:34.497) - MainThread (12452):
Initializing braille input
INFO - brailleInput.initialize (08:06:34.497) - MainThread (12452):
Braille input initialized
DEBUG - core.main (08:06:34.497) - MainThread (12452):
Initializing braille
INFO - braille.initialize (08:06:34.497) - MainThread (12452):
Using liblouis version 3.28.0
INFO - braille.initialize (08:06:34.497) - MainThread (12452):
Using pySerial version 3.5
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (08:06:34.497) - MainThread (12452):
registering pre_configSave action: <class 'brailleDisplayDrivers.papenmeier.BrailleDisplayDriver'>
INFO - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.connectUSB (08:06:34.559) - MainThread (12452):
connectUSB success
INFO - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.__init__ (08:06:34.617) - MainThread (12452):
Found EL80c
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (08:06:34.617) - MainThread (12452):
loading braille papenmeier
INFO - braille.BrailleHandler._setDisplay (08:06:34.617) - MainThread (12452):
Loaded braille display driver 'papenmeier', current display has 80 cells.
DEBUG - core.main (08:06:34.617) - MainThread (12452):
Initializing vision
DEBUG - core.main (08:06:34.617) - MainThread (12452):
Initializing displayModel
DEBUG - core.main (08:06:34.617) - MainThread (12452):
Initializing GUI
DEBUG - config.isInstalledCopy (08:06:34.627) - MainThread (12452):
Unable to find isInstalledCopy registry key RegistryKey.INSTALLED_COPY- this is not an installed copy.
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
2024.1beta4
#### Windows version:
Microsoft Windows 11 Professional Version 23H2 (OS Build 22631.3007), System Type x64
#### Name and version of other software in use when reproducing the issue:
No other software
#### Other information about your system:
Lenovo ThinkStation P3 Tower with 16 GB RAM
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Alphas and Betas since December 2023 with same results
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
Fixes #16072

### Summary of the issue:
As seen in a dump file provided by @irrah68 when debugging #16072 , NVDA can hang on exit while trying to destruct an instance of the CUIAutomation8 COMClass object:
<summary>
Call stack
</summary>
<details>
<pre>
win32u.dll!_NtUserMsgWaitForMultipleObjectsEx@20()	Unknown
user32.dll!MsgWaitForMultipleObjectsEx()	Unknown
combase.dll!CCliModalLoop::BlockFn(void * * ahEvent, unsigned long cEvents, unsigned long * lpdwSignaled) Line 2116	C++
combase.dll!ClassicSTAThreadWaitForHandles(unsigned long dwFlags, unsigned long dwTimeout, unsigned long cHandles, void * * pHandles, unsigned long * pdwIndex) Line 54	C++
combase.dll!CoWaitForMultipleHandles(unsigned long dwFlags, unsigned long dwTimeout, unsigned long cHandles, void * * pHandles, unsigned long * lpdwindex) Line 126	C++
combase.dll!CGIPTable::_RevokeInterfaceFromGlobal(unsigned long dwCookie, bool bPostedRevoke, bool waitIfBusy) Line 1010	C++
combase.dll!CGIPTable::RevokeInterfaceFromGlobal(unsigned long dwCookie) Line 935	C++
uiautomationcore.dll!ViewManagerEventTracker::Uninitialize(void)	Unknown
uiautomationcore.dll!ClientEventManager::~ClientEventManager(void)	Unknown
uiautomationcore.dll!CUIAutomation::~CUIAutomation(void)	Unknown
uiautomationcore.dll!ATL::CComObject<class CUIAutomation8>::`scalar deleting destructor'(unsigned int)	Unknown
uiautomationcore.dll!ATL::CComObject<class CUIAutomation8>::Release(void)	Unknown
[Inline Frame] UIARemote.dll!wil::com_ptr_t<IUIAutomation,wil::err_exception_policy>::{dtor}() Line 260	C++
[Inline Frame] UIARemote.dll!wil::object_without_destructor_on_shutdown<wil::com_ptr_t<IUIAutomation,wil::err_exception_policy>>::{dtor}() Line 2209	C++
UIARemote.dll!UiaOperationAbstraction::`anonymous namespace'::`dynamic atexit destructor for 'g_automation''()	C++
ucrtbase.dll!<lambda>(void)()	Unknown
ucrtbase.dll!__crt_seh_guarded_call<int>::operator()<<lambda_69a2805e680e0e292e8ba93315fe43a8>,<lambda>(void) &,<lambda>(void)>()	Unknown
ucrtbase.dll!__execute_onexit_table()	Unknown
UIARemote.dll!__scrt_dllmain_uninitialize_c() Line 398	C++
UIARemote.dll!dllmain_crt_process_detach(const bool is_terminating) Line 182	C++
</pre>
</details>
In short, it looks as if the destruction of the CUIAutomation8 COMClass object held by the UIA abstraction Remote Operations library locks up as it is happening from a different thread from where it was created. It was originally created in NvDA's UIA MTA thread, but it is being automatically cleaned up by the CRT of NVDA's UIARemote.dll in NVDA's main thread.
I'm not entirely sure why this is only a problem on @irrah68's machine, and why it is more likely to happen with the UIA Rate Limited event handler in #14888.
Either way though, NVDA is not cleaning it up correctly.

### Description of user facing changes
NVDA is less likely to hang on NvDA exit.

### Description of development approach
* Add a `cleanup` function to `UIARemote.dll` which calls the UIA abstraction remote operations library's `cleanup` function. This function frees all remote contexts, but most importantly, releases the CUIAutomation8 COMClass object which was  passed in on initialization.
* Add a `terminate` function to `UIAHandler/remote.py` which calls UIARemote.dll's `cleanup` function.
* at the end of UIA's MTA thread in Python, after removing event handlers, finally call `UIAHandler.remtoe.terminate`, ensuring that the UIA abstraction remote ops library is correctly cleaned up in the UIA MTA thread, where it was originally initialized.

### Testing strategy:
* Restarted NVDA multiple times. Ensured the NvDA's log showed the appropriate log messages in UIARemote.dll's `cleanup` method.
* [x] @irrah68 has tested a try build of this pr based on master and has confirmed the issue has been fixed for them.

### Known issues with pull request:
None known.

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by CyrilleB79** [comment]
@michaelDCurran please modify the issue number being fixed (twice) in the initial description. #16072 and not #16074.

**Comment by michaelDCurran** [comment]
@CyrilleB79 oops, thanks. I've fixed this up now.

File: nvdaHelper/UIARemote/UIARemote.cpp [hunk 1]
```diff
@@ -153,6 +153,17 @@ extern "C" __declspec(dllexport) bool __stdcall initialize(bool doRemote, IUIAut
 	return true;
 }
 
+// Cleans up the remote opperations library.
+extern "C" __declspec(dllexport) void __stdcall cleanup() {
+	if(_isInitialized) {
```
Comment (seanbudd) [inline nvdaHelper/UIARemote/UIARemote.cpp:158]:
```suggestion
	if (_isInitialized) {
```

File: nvdaHelper/UIARemote/UIARemote.cpp [hunk 2]
```diff
@@ -153,6 +153,17 @@ extern "C" __declspec(dllexport) bool __stdcall initialize(bool doRemote, IUIAut
 	return true;
 }
 
+// Cleans up the remote opperations library.
```
Comment (seanbudd) [inline nvdaHelper/UIARemote/UIARemote.cpp:156]:
```suggestion
// Cleans up the remote operations library.
```

**Review by seanbudd — DISMISSED** [review]
