### PR TITLE
MS Word object model: Always fetch range information

### LINKED ISSUE #15019: Unchecking "Report Comments" and "Report Titles" in the document formatting panel will cause ms word to crash and quit.
### Steps to reproduce:
1. NVDA+ Ctrl +D to open the document format setting panel, uncheck "ReportComments" and "ReportHeadings", and then save the settings.
2. In the "Use UI Automation to access Microsoft Word document controls" in the advanced settings panel, select "" "Default".
3. Press Win+R and enter 'winword' to open MS Word and create a new "blank document".
### Actual behavior:
MSWord crashes and quits, NVDA recovers from freeze.
P.S. This is only reproducible when Word uses object model, not UIA.
### Expected behavior:
MSWord and NVDA both work fine.
### NVDA logs, crash dumps and other attachments:
[NVDA-log.txt](https://github.com/nvaccess/nvda/files/11781985/NVDA-log.txt)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.1, alpha-28430,3920fa58 
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3086
#### Name and version of other software in use when reproducing the issue:
MSO (Version 2305 Build 16.0.16501.20074)
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Fixes #15019 

### Summary of the issue:
NVDA only fetches object text range information if "report headings" and "report comments and notes" are enabled.
This only happens when using the object model.
This causes a crash when attempting to update the caret, as we try to fetch range information that hasn't been generated by nvdaHelper.

### Description of user facing changes
Fix crash in Microsoft Word when Document formatting options "report headings" and "report comments and notes" were not enabled.
### Description of development approach
Always fetch range information, regardless of these options.
### Testing strategy:
Test STR in #15019  with UIA and Object model
### Known issues with pull request:
None
### Change log entries:
```t2t
Bug fixes
- Fix crash in Microsoft Word when Document formatting options "report headings" and "report comments and notes" were not enabled. (#15019)
```

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

File: nvdaHelper/remote/winword.cpp [hunk 1]
```diff
@@ -1145,11 +1145,33 @@ void winword_getTextInRange_helper(HWND hwnd, winword_getTextInRange_args* args)
...
+			S_OK == _com_dispatch_raw_method(
+				pDispatchParagraphs,
+				wdDISPID_PARAGRAPHS_ITEM,
+				DISPATCH_METHOD,
+				VT_DISPATCH,
+				&pDispatchParagraph,
+				L"\x0003",
+				1
+			)
+			&&pDispatchParagraph
```
Comment (seanbudd) [inline nvdaHelper/remote/winword.cpp:1167]: Fix lint

```suggestion
			&& pDispatchParagraph
```

**Review by michaelDCurran — APPROVED** [review]
