### PR TITLE
Merge all vbufBackend dlls into nvdaHelperRemote.dll

### LINKED ISSUE #7641: In latest next builds, trying to update next, then makes browser events die until reboot.
### Background:

There's been a bug in NVDA for years that when we load source copies of NVDA, events in browsers fail to talk to us. Somehow, I always ignored this in source, because core developers experienced it too, however, with the introduction of https://github.com/nvaccess/nvda/issues/7563 I believe this got much worse. Every time I update next, NVDA stops responding to dynamic events until I reboot. I can still nvda+f5 to refresh however.

### Hypothesis

Since the library version is changing every time our version updates, somehow, the old code is receiving events and the new code isn't. There's something I think with this, because if I change from binary to source, and back to binary under proper working conditions, the path used to be the same, and the code would work just fine. I propose introducing a try build of NVDA that beeps upon every event responded to in a vbuff. That way, I can run that version installed, reboot, install next, then try to see if I get beeps, suggesting the old code is running.

### Steps to reproduce:

Under any earlier than latest <next|master|you choose> build of NVDA

1. visit google.com.
2. type chickens into the search box.
3. now, go to the search box again, and type "horses"

    Expected: you can press 2 to find search results for horses.
    Actual: this works.
4. Now, repeat steps 1-3 again, after updating NVDA (So long as you have a binary version you are fine). Update to either latest next or master.
    Expected: You get search results for Horses.
    Actual: You get search results for Chickens, if you get search results for anything.
5. Now, press NVDA+f5.
    Note how you now have search results for horses.

### System configuration:
NVDA version: anything post https://github.com/nvaccess/nvda/issues/7563

NVDA Installed or portable: Needs to be a binary build, other than that it doesn't matter.

Does the issue still occur after restarting your PC? No

Have you tried any other versions of NVDA? I've tried source, and the several next builds.

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
Closes #7641

### Summary of the issue:
After updating NVDA while Firefox or Chrome web browsers are open, NVDA's virtualBuffers in these browsers fail to reflect further updates to web pages, and in some cases the browser crashes.
This is caused by:
1.  Although the old NVDA has quit, and the new NVDA has started, Windows may be slow at unloading the old NVDA's nvdaHelperRemote.dll. The old dll is fully terminated, but still resides in memory for a while.
2. Focus moves into the web browser, and Windows loads the new NVDA's nvdaHelperRemote.dll into the browser, via an in-process winEvent.
3. The new NVDA detects a document in a web browser and prepairs to create a virtualBuffer, by making an rpc call to the new nvdaHelperRemote.dll, requesting it to load the correct vbufBackend dll and create the virtualBuffer.
4. The vbufBackend dll is linked against nvdaHelperRemote, so Windows tries to resolve this linkage by newly loading, or reusing an existing loaded nvdaHelperRemote.dll.
5. As Two different nvdaHelperRemote dlls are loaded, Windows seems to choose the oldest one.
6. In this case, Windows chooses the old NVDA's nvdaHelperRemote.dll.
7. From now on, the virtualBuffer makes calls to the wrong nvdaHelperRemote, which is in fact terminated, and therefore it cannot make use of features such as nvdaHelperRemote's winEvent registrations etc. In deed, it is likely that one of the calls may completely crash the app, if for instance Windows does eventually unload the old NVDAHelperRemote.dll.

### Description of how this pull request fixes the issue:
This PR removes the possibility of loading the wrong nvdaHelperRemote.dll by moving all the virtualBuffer code into nvdaHelperRemote.dll itself, which removes the need for the vbufBackend dlls all together.
The vbufBackend dls were origianlly separate as there was some hope that perhaps one day we might allow custom backends. However, in truth this was never fully possible due to other limitations in NVDA. Another reason was that vbufBackend dlls may link against some specific heavy-weight libraries, which in many cases would not be required in all apps except the ones that actually required that specifica virtualBuffer. In truth though, none of the vbufBackend dlls link against anything else other than what nvdaHelperRemote already links against.
A part from solving the dynamic changes dying, and the crashes, a further advantage is that NvDA's size shrinks significantly as  we were carrying around about 12 vbufBackend dlls, all containing their own static copy of the CRT. Now, the virtualBuffers all share the one crt in nvdaHelperRemote.dll.
 
### Testing performed:
Ran NVDA. Opened documents that require virtualBuffers in Firefox, Chrome, Internet Explorer, and webKit (iTunes). AdobeAcrobat, AdobeFlash and LotusNotes are yet to be tested. However, the only way these could fail is if the name if the virtualBuffer has been typed incorrectly in the source code. The rest of the code stays the same.

### Known issues with pull request:
None.

### Change log entry:
Bug fixes:
After updating NVDA, NvDA no longer fails to notice updates to document in Firefox and these browsers should no longer crash after the NVDA update. (#7641)

### CODE REVIEW

File: nvdaHelper/remote/vbufRemote.cpp [hunk 1]
```diff
@@ -16,30 +16,39 @@ This license can be found at:
...
-	wsprintf(backendPath,L"%s\\VBufBackend_%s.dll",dllDirectory,backendName);
-	HINSTANCE backendLibHandle=LoadLibrary(backendPath);
-	if(backendLibHandle==NULL) return NULL;
-	VBufBackend_create_proc createBackend=(VBufBackend_create_proc)GetProcAddress((HMODULE)(backendLibHandle),"VBufBackend_create");
-	if(createBackend==NULL) {
-		FreeLibrary(backendLibHandle);
-		return NULL;
-	} 
+
+	auto i=VBufBackendFactoryMap.find(backendName);
```
Comment (feerrenrut) [inline nvdaHelper/remote/vbufRemote.cpp]: If `backendName` is `nullptr` then I don't think it will convert to a `wstring`

```suggestion
	if(!backendName){
		LOG_ERROR(L"BackendName is nullptr");
		return nullptr;
	}
	auto i=VBufBackendFactoryMap.find(backendName);
```

File: nvdaHelper/remote/vbufRemote.cpp [hunk 2]
```diff
@@ -16,30 +16,39 @@ This license can be found at:
...
 	VBufBackend_t* backend=createBackend(docHandle,ID);
 	if(backend==NULL) {
-		FreeLibrary(backendLibHandle);
 		return NULL;
 	}
-	backendLibHandles[backend]=backendLibHandle;
 	backend->initialize();
+	// Stop nvdaHelperRemote from being unloaded while a backend exists.
+	HINSTANCE tempHandle=nullptr;
+	if(!GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS,(LPCTSTR)dllHandle,&tempHandle)) {
```
Comment (feerrenrut) [inline nvdaHelper/remote/vbufRemote.cpp]: Could we replace the c-style cast in here `(LPCTSTR)dllHandle`

File: nvdaHelper/vbufBackends/mshtml/mshtml.cpp [hunk 3]
```diff
@@ -23,35 +23,26 @@ This license can be found at:
...
-
-BOOL WINAPI DllMain(HINSTANCE hModule,DWORD reason,LPVOID lpReserved) {
-	if(reason==DLL_PROCESS_ATTACH) {
-		_CrtSetReportHookW2(_CRT_RPTHOOK_INSTALL,(_CRT_REPORT_HOOKW)NVDALogCrtReportHook);
-		backendLibHandle=hModule;
-		WM_HTML_GETOBJECT=RegisterWindowMessage(L"WM_HTML_GETOBJECT");
-	}
-	return TRUE;
-}
+UINT WM_HTML_GETOBJECT=RegisterWindowMessage(L"WM_HTML_GETOBJECT");
```
Comment (feerrenrut) [inline nvdaHelper/vbufBackends/mshtml/mshtml.cpp]: This potentially subtly changes the order/timing of when this happens. This might not be a problem, but it's worth being aware of. If possible, I would prefer to see an explicit initialisation function.

**Review by feerrenrut — CHANGES_REQUESTED** [review]

**Comment by michaelDCurran** [comment]
@feerrenrut  I have addressed your review comments.

**Review by feerrenrut — APPROVED** [review]

**Comment by JulienCochuyt** [comment]
Apologies for disturbing if this is irrelevant: Beware two branches were created with similar names but different case: mergedVbufBackendLibs (lower b) and mergedVBufBackendLibs (upper B), the former being ahead of the latter by 5 commits.

**Comment by leonardder** [comment]
We can remove the mergedVBufBackendLibs branch, but I'm not going to do that without @michaeldcurran's consent.
