### PR TITLE
VBufStorage:  do not delete reference nodes prematurely when replacing subtrees

### LINKED ISSUE #8924: Crash in VBufStorage_buffer_t::deleteNode in Firefox Nightly with Gmail
### Steps to reproduce:

1. I was in a Gmail conversation.
2. Pressed Space on the More Actions for the conversation in the upper tool bar.
3. Arrowed down in the menu, wanted to add a filter. Got to the Add To Tasks item.
4. Press DownArrow once more.

### Actual behavior:

Reproducible crash that closed Firefox. Sometimes, Crash Reporter doesn't even come up. But once it did, and it gave me [this crash report](https://crash-stats.mozilla.com/report/index/6c6c3806-ad3e-4b1d-b625-37f720181106).

### Expected behavior:

No crash.

#### NVDA Installed/portable/running from source:

Installed.

#### NVDA version:

NVDA version alpha-16220,87eb36f8

#### Windows version:

Windows 10 insider 18272.

#### Name and version of other software in use when reproducing the issue:

Firefox 65.0a1 Nightly from November 6.

#### Other information about your system:

Gmail is in New Design, I believe this is the default now, and you cannot eve turn that off any more. It's the standard Gmail, not G Suite.

#### Does the issue still occur after restarting your PC?

Yes. Reproducible on my system.

#### Have you tried any other versions of NVDA?

Yes, 2018.3.x does not crash. I suspect this is a result of either the VBuf speedup or the merging of DLLs, or both.

CC @michaelDCurran @jcsteh.

### LINKED ISSUE #9402: NVDA crashes Firefox Nightly when choosing label during filter creation in Gmail.
### Steps to reproduce:
1. Open firefox Nightly, login to Gmail.
2. Perform a search and then click advanced search options.
3. Click create filter.
4. Check Apply the label, move to button for selecting a label, press it with space, and try to navigate in the newly opened menu.
### Actual behavior:
Firefox Nightly crashes, the following is written in the NVDA log
ERROR - eventHandler.executeEvent (19:12:48.443):
error executing event: gainFocus on <NVDAObjects.IAccessible.mozilla.BrokenFocusedState object at 0x0531EBF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "C:\Users\Lukasz\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 426, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "appModules\firefox.pyc", line 24, in event_stateChange
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1448, in event_gainFocus
  File "textInfos\offsets.pyc", line 458, in expand
  File "virtualBuffers\__init__.pyc", line 376, in _getUnitOffsets
  File "textInfos\offsets.pyc", line 437, in _getUnitOffsets
  File "textInfos\offsets.pyc", line 306, in _getCharacterOffsets
  File "virtualBuffers\__init__.pyc", line 230, in _getTextRange
WindowsError: [Error 1726] remote invocation of a procedure failed.

the crash report from Nightly is here:
https://crash-stats.mozilla.org/report/index/7f8b7e21-9ef0-4e44-b758-8c0b30190323
### Expected behavior:
The list of the labels should be navigable.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA version alpha-16941,e3b2e797

#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
Firefox Nightly 68.0a1 (2019-03-23) (64-bit)
#### Other information about your system:
With JAWS Nightly doesn't crash in this situation.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No
cc @jcsteh @MarcoZehe

### LINKED ISSUE #10175: Vbuf backend crashes when moving options between list boxes
### Steps to reproduce:

1. Open this test case in Firefox:
    `data:text/html,<body onkeydown="if (event.key == 'ArrowDown') { let oldActive = owner.getAttribute('aria-activedescendant'); let newActive = oldActive == 'item1' ? 'item2' : 'item1'; owner.setAttribute('aria-owns', newActive); owner.setAttribute('aria-activedescendant', newActive); }"><div role="listbox"><div id="item1" role="option"><div>item1</div></div><div id="item2" role="option"><div>item2</div></div></div><div id="owner" role="listbox" tabindex="0" aria-owns="item1" aria-activedescendant="item1"><div></div></div></body>`
2. Tab so that the list box option has focus.
3. Switch to focus mode.
4. Press down arrow. If no crash, press down arrow again.

### Actual behavior:
Crash in VBufStorage_buffer_t::getLineOffsets. For example: https://crash-stats.mozilla.org/report/index/d669328d-964a-42e0-ac10-ea9420190909

### Expected behavior:
No crash.

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
alpha-18290,7b5cd2d0

#### Windows version:
Windows 10 Version 1903 (OS Build 18362.10015)

#### Name and version of other software in use when reproducing the issue:
Firefox nightly 71.0a1 (2019-09-08) (64-bit)

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

### Additional info
I wrote this test case in attempting to distill an issue experienced on Gmail. The Gmail crash occurs in VBufStorage_buffer_t::deleteSubtree. While different, I'm guessing it's related; these are both to do with buffer corruption. I'm hoping a fix for the test case above will deal with the Gmail crash too.  If not, I can file a separate bug for the Gmail crash.

The Gmail crash was reported by @MarcoZehe in https://bugzilla.mozilla.org/show_bug.cgi?id=1579610 . Here are the STR he provided (and I can immediately reproduce this too):

> 1. Log into Gmail.
> 2. Open a conversation.
> 3. Open the More menu inside the conversation view, and choose "Filter hese messages".
> 4. Accept whatever it presents you and choose the Create Filter link at the bottom.
> 5. On the next page, check the box that says Apply Label.
> 6. Tab once to the Choose Label dropdown, and choose a label by arrowing to it and pressing Enter.
>    * Expected: Focus should return to the closed dropdown where the label has been chosen.
>    * Actual: Either Firefox crashes, and NVDA keeps running, or Firefox and NVDA close down alltogether, and no crash reporter comes up. I had both happen to me, and one instance where only Firefox crashed, brought up the above crash report.

CC @MichaelDCurran.

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
Fixes #10175 
Fixes #9402
Fixes #8924
Replaces pr #8930

### Summary of the issue:
NVDA could crash the web browser if a page moved an accessibility node from one subtree on the page to another, either by moving a DOM node directly, or when setting aria-owns dynamically. The crash became much more likely if two nodes were swapped with each other at the same time, such as in issue #10175 .
The crash was occuring because VBufStorage_buffer_t::replaceSubtrees would move reference nodes for reuse, and then straight away remove the old subtree and replace it with the content of the temporary buffer, However reference nodes in other subtrees may be further replaced, containing their own reference nodes which may reference nodes that have already been removed. 
 
### Description of how this pull request fixes the issue:
VBufsTorage_buffer_t::replaceSubtrees now moves reference nodes on all temp buffers first, and only then removes the old subtrees and replaces them with the content of the temp buffers.
This pr also reverts code in pr #8930 which removes the limitation in VBufBackend_t::reuseExistingNodeInRender where it would refuse to return an existing node if it did not share the same parent. This particular code was flawed as it never took descendants into account. For example in issue #10175:  If item1 was moved from container2 to container1, although item1 itself wouldn't be reused as the parents differ, item1's child div would be reused, therefore not avoiding a possible crash. Now the underlying issue is addressed, it is now hopefully safe enough to reuse nodes from differing parents, though we could obviously reinstate that code if we wanted.

### Testing performed:
Performed testcase in #10175. Firefox no longer crashes.
 Performed testcase in #9402. Firefox no longer crashes.
 Performed testcase in #8924. Firefox no longer crashes.

### Known issues with pull request:
None known.

### Change log entry:
Addressed several crashes in Gmail seen in both Firefox and Chrome when interacting with  particular popup menus such as when creating filters or changing certain Gmail settings.

### CODE REVIEW

**Comment by michaelDCurran** [comment]
@MarcoZehe  Would you mind testing this pr with your one or more Gmail crashes please?
Try build: https://ci.appveyor.com/api/buildjobs/exsihk38wrq0c24q/artifacts/output%2Fnvda_snapshot_try-i10175-18589%2C79a1db60.exe

**Comment by michaelDCurran** [comment]
Currently this pr is showing 3 commits. That first one is already on master. I think I forgot to push my local master before I branched and created this pr. Thus github saw it on this branch first. Not sure if it will correct itself...

**Comment by leonardder** [comment]
How about doing a rebase on latest master and then force push? I don't think that's that much of a problem before review comments have been made.

**Comment by michaelDCurran** [comment]
Weirdly latest master is the commit in question. So a rebase literally 
does nothing. Perhaps once something else gets merged to master it will 
either correct itself or I can try the rebase idea.

File: nvdaHelper/vbufBase/backend.cpp [hunk 1]
```diff
@@ -284,10 +284,6 @@ VBufStorage_controlFieldNode_t* VBufBackend_t::reuseExistingNodeInRender(VBufSto
 		LOG_DEBUG(L"existing node has no parent. Not reusing.");
 		return nullptr;
 	}
-	if(existingParent->identifier!=parent->identifier) {
```
Comment (jcsteh) [inline nvdaHelper/vbufBase/backend.cpp]: There's a comment a few lines above this which should probably be removed:

> ```
>        // We only allow reusing nodes that share the same parent.
>        // I.e. we don't allow reusing a node that existed in an entirely different part of the tree.
>        // If we did, this could possibly cause corruption in the virtualBuffer as a node might move between two unrelated updates.
> ```

**Review by jcsteh — APPROVED** [review]
Nice catch! Thanks!

**Comment by MarcoZehe** [comment]
Fix confirmed, thank you! Does this have a chance of being backported to a possible 2019.2.1 release?

**Review by feerrenrut — CHANGES_REQUESTED** [review]

**Review by feerrenrut — APPROVED** [review]
Thanks Mick
