### PR TITLE
Report background and highlighted text in MS Word

### LINKED ISSUE #5866: Report background and highlighting colors in Microsoft Word
I noticed that NVDA is unable to report background and highlighting color changes in Microsoft Word. Check [the attachment](https://github.com/nvaccess/nvda/files/208986/Color.reporting.zip) for an example.

Steps to reproduce
1. Type a two lines of text in an empty document
2. Select the second line of text
3. Press alt+h,i and select a highlighting color
4. Select again, press alt+h,h and select a differenc background color
5. Arrow up and down in the document with color reporting enabled

Actual result: NVDA reports no difference
Proposed result: NVDA reports both background and highlighting color changes

### LINKED ISSUE #7396: Microsoft Word Highlighted text
I,
form my work, I get from my colleges, different word processing documents. These documents (*.doc and *.docx), contain highlighted text and barred text . 
I have important information about this text,but i can not understand by nvda, i do not use braille.

Can you put these features in nvda?

Thank you.

### LINKED ISSUE #12101: NVDA cannot read MS Word highlighting without checking "Use UI Automation to access Microsoft Word document controls.
### Steps to reproduce:

1. Download the attached test.zip and unzip it.
2. Open the unzipped test.docx
3. Make sure "Use UI Automation to access Microsoft Word document controls" is unchecked in the NVDA advanced settings
4. Ensure that "Colors" is checked in the NVDA document formatting settings
5. Use the arrow keys to navigate through this document.
6. Check "Use UI Automation to access Microsoft Word document controls when available" in the NVDA advanced settings.
7. Use the arrow keys to navigate through this document.

### Actual behavior:
1. Execute step (5) NVDA will read out "I am a student."
2. Execute step (7) NVDA will read out "I bright yellow background am white background a grey background student white background."

### Expected behavior:
Both step (5) and step (7) should be read aloud as """I bright yellow background am white background a grey background student white background."

#### NVDA installed/portable/running from source:
installed andportable
#### NVDA version:
NVDA2020.3 andNVDA2020.4
#### Windows version:
Windows 10 20H2 (64-bit) build 19042.844

#### Name and version of other software in use when reproducing the issue:
Microsoft Word for Microsoft 365 MSO (16.0.13628.20318) 64-bit 

#### Other information about your system:
none

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If addons are disabled, is your problem still occuring?
yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes

### PR DESCRIPTION
**Pull request by ABuffEr**
### Link to issue number:

Fixes #5866, fixes #7396, fixes #12101

### Summary of the issue:

In these years, Microsoft Word users working without UIA had no feedback about background and highlighting colors, often used by colleagues, teachers and students.

UIA has provided a partial solution when available, but its support for these features is far from perfect (see later).

### Description of user facing changes

Assuming UIA is not available/forcibly enabled:

* when color reporting is enabled in formatting preferences, users will hear background colors too;
* when marked/highlighted text reporting is enabled in formatting preferences, users will hear highlighting colors ("highlighted in {color}" and "no highlighting"), regardless of color reporting.

### Description of development approach

It was very difficult to find a way, so I'll add some details.

Initially, I used VBA objects approach, querying [Paragraph.Shading](https://github.com/MicrosoftDocs/VBA-Docs/blob/main/api/Word.Paragraph.Shading.md)[.BackgroundPatternColor](https://github.com/MicrosoftDocs/VBA-Docs/blob/main/api/Word.Shading.BackgroundPatternColor.md) and [Range.HighlightColorIndex](https://github.com/MicrosoftDocs/VBA-Docs/blob/main/api/Word.Range.HighlightColorIndex.md) over a winwordDocument.Range to calculate each time, so it was very slow.

Then I found [this document](https://github.com/nvaccess/nvda/wiki/Using-COM-with-NVDA-and-Microsoft-Word) and, after having understood what I needed and how to find the required wdDISPID_ constants, I was able to move all work on the C++ component of nvdaHelperRemote related to winword, that appears very much faster.

In window/winword.py, to take advantage of winwordColorToNVDAColor work, I added also a dict that collects indexes from [wdColorIndex](https://github.com/MicrosoftDocs/VBA-Docs/blob/main/api/Word.WdColorIndex.md) and decimal values from [wdColor](https://github.com/MicrosoftDocs/VBA-Docs/blob/main/api/Word.WdColor.md).

About speech, I had to introduce a new format field, highlight-color.

Now, UIA: sure, it already covers background and highlight colors, but expose them as the same attribute, via UIA_BackgroundColorAttributeId (and no, I asked, even visually they are distinct). There is an AnnotationType_Highlighted identifier, but it seems to not be used in this scenario.

Locally I have a possible workaround, based on the fact that, as you see in Word Home menu, highlighting color is applied to characters, background color to paragraphs; so, if textRange has a background-color, I compare it to that retrieved from paragraph and, if I receive IUnknown/MixedAttributeValue, I assume the initial one is an highlighting color and try to get the real background color from "\r" EOL.

But I'm not totally convinced, so I not included it in this PR for now.

### Testing strategy:

See #5866 str and attachment.

Unfortunately, I have access only to a working copy of Word for Microsoft 365 MSO (Version 2302 Build 16.0.16124.20000), 64 bit.

I tried to avoid any dangerous assumption in C++, according to existing code, but a lot of testing is required, maybe.

### Known issues with pull request:

Apparently, highlighting is not correctly reported if it's not applied on whole word (investigating).

Highlighting announcements could be too verbose, I considered to use "marked in {color}" and "not marked", but then leaved as is for clarity against Word feature. Suggestions are welcome.

Even the fact highlighted (colored) text is not reported when color reporting is enabled could be confusing for some users, so, again, a discussion is welcome.

### Change log entries:

New features
Changes
Bug fixes

For Developers
- new highlight-color format field.

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by Adriani90** [comment]
Wow this is great work, thank you for taking this up I was trying to find a solution for this for a very long time. This will improve the way blind and sighted people work together in a document alot.

Is there also a possibility to implement a key stroke for the browse mode to jump between highlighted text?

**Comment by cary-rowen** [comment]
Thanks, great work.
Yep, it would be nice to have a key to jump between "highlights".

**Comment by ABuffEr** [comment]
Hi,
first, thanks for appreciation :)
About quick nav, I think it's possible, but I don't know how much it's fast. I'm studying the relative code (a lot of small classes).
Have you concerns about the aspects I mentioned under "Known issues"?

**Comment by CyrilleB79** [comment]
Regarding the key to jump between highlight, that's a completely valid request. But it would better to handle this in a subsequent PR. So please, open an issue (if not yet existing) or comment in existing issue.

**Comment by leonardder** [comment]
Might be related to #9527

**Comment by ABuffEr** [comment]
Thanks, I'll comment there about quick nav and a new formatting helper (before to elaborate this PR, I worked on a new, related add-on).

**Comment by ABuffEr** [comment]
Hi,
I initially declared PR as a draft, as suggested in PR template, but the committed parts are ready since I opened it.
If covering UIA is preferred, I can commit also that part, even if it's more a workaround than a solution.

File: nvdaHelper/remote/winword.cpp [hunk 1]
```diff
@@ -525,9 +526,18 @@ void generateXMLAttribsForFormatting(IDispatch* pDispatchRange, int startOffset,
 	if((formatConfig&formatConfig_reportLineNumber)&&(_com_dispatch_raw_method(pDispatchRange,wdDISPID_RANGE_INFORMATION,DISPATCH_PROPERTYGET,VT_I4,&iVal,L"\x0003",wdFirstCharacterLineNumber)==S_OK)) {
 		formatAttribsStream<<L"line-number=\""<<iVal<<L"\" ";
 	}
-	if((formatConfig&formatConfig_reportAlignment)||(formatConfig&formatConfig_reportParagraphIndentation)||(formatConfig&formatConfig_reportLineSpacing)) {
+	if((formatConfig&formatConfig_reportColor)||(formatConfig&formatConfig_reportAlignment)||(formatConfig&formatConfig_reportParagraphIndentation)||(formatConfig&formatConfig_reportLineSpacing)) {
```
Comment (seanbudd) [inline nvdaHelper/remote/winword.cpp:529]: Fix formatting for readability

```suggestion
	if (
		(formatConfig & formatConfig_reportColor)
		|| (formatConfig & formatConfig_reportAlignment)
		|| (formatConfig & formatConfig_reportParagraphIndentation)
		||(formatConfig & formatConfig_reportLineSpacing)
	) {
```

File: nvdaHelper/remote/winword.cpp [hunk 2]
```diff
@@ -525,9 +526,18 @@ void generateXMLAttribsForFormatting(IDispatch* pDispatchRange, int startOffset,
 	if((formatConfig&formatConfig_reportLineNumber)&&(_com_dispatch_raw_method(pDispatchRange,wdDISPID_RANGE_INFORMATION,DISPATCH_PROPERTYGET,VT_I4,&iVal,L"\x0003",wdFirstCharacterLineNumber)==S_OK)) {
 		formatAttribsStream<<L"line-number=\""<<iVal<<L"\" ";
 	}
-	if((formatConfig&formatConfig_reportAlignment)||(formatConfig&formatConfig_reportParagraphIndentation)||(formatConfig&formatConfig_reportLineSpacing)) {
+	if((formatConfig&formatConfig_reportColor)||(formatConfig&formatConfig_reportAlignment)||(formatConfig&formatConfig_reportParagraphIndentation)||(formatConfig&formatConfig_reportLineSpacing)) {
 		IDispatchPtr pDispatchParagraphFormat=NULL;
 		if(_com_dispatch_raw_propget(pDispatchRange,wdDISPID_RANGE_PARAGRAPHFORMAT,VT_DISPATCH,&pDispatchParagraphFormat)==S_OK&&pDispatchParagraphFormat) {
+			if(formatConfig&formatConfig_reportColor) {
```
Comment (seanbudd) [inline nvdaHelper/remote/winword.cpp:532]: Lint

```suggestion
			if (formatConfig & formatConfig_reportColor) {
```

File: nvdaHelper/remote/winword.cpp [hunk 3]
```diff
@@ -525,9 +526,18 @@ void generateXMLAttribsForFormatting(IDispatch* pDispatchRange, int startOffset,
...
 		IDispatchPtr pDispatchParagraphFormat=NULL;
 		if(_com_dispatch_raw_propget(pDispatchRange,wdDISPID_RANGE_PARAGRAPHFORMAT,VT_DISPATCH,&pDispatchParagraphFormat)==S_OK&&pDispatchParagraphFormat) {
+			if(formatConfig&formatConfig_reportColor) {
+				IDispatchPtr pDispatchParagraphFormatShading=NULL;
+				if(_com_dispatch_raw_propget(pDispatchParagraphFormat,wdDISPID_PARAGRAPHFORMAT_SHADING,VT_DISPATCH,&pDispatchParagraphFormatShading)==S_OK&&pDispatchParagraphFormatShading) {
+					int bgColor=0;
+					if(_com_dispatch_raw_propget(pDispatchParagraphFormatShading,wdDISPID_SHADING_BACKGROUNDPATTERNCOLOR,VT_I4,&bgColor)==S_OK) {
+						formatAttribsStream<<L"background-color=\"" << bgColor <<L"\" ";
+					}
+				}
```
Comment (seanbudd) [inline nvdaHelper/remote/winword.cpp:539]: please try and lint all of these changes with appropriate spacing around operators.

File: source/speech/speech.py [hunk 4]
```diff
@@ -2442,6 +2442,17 @@ def getFormatFieldSpeech(  # noqa: C901
 				# Translators: Reported when text is no longer marked
 				else _("not marked"))
 			textList.append(text)
+		# color-highlighted text in Word
+		hlColor = attrs.get("highlight-color")
+		oldHlColor = attrsCache.get("highlight-color") if attrsCache is not None else None
+		if (hlColor or oldHlColor is not None) and hlColor != oldHlColor:
```
Comment (seanbudd) [inline source/speech/speech.py:2448]: why is `hlColor` in the first or statement? can `hlColor` be falsey?

File: source/NVDAObjects/window/winword.py [hunk 5]
```diff
@@ -219,6 +219,28 @@
 	wdThemeColorText2:msoThemeDark2,
 }
 
+# map index from wdColorIndex to decimal values in wdColor
+highlightColors = {
```
Comment (seanbudd) [inline source/NVDAObjects/window/winword.py:223]: Could you document the relevant enums here?

https://learn.microsoft.com/en-us/office/vba/api/word.wdcolorindex
https://learn.microsoft.com/en-us/office/vba/api/word.wdcolor

It would be even better to emulate these enums with python `IntEnum` and then making the mapping as follows:

```suggestion
class WinWordColorIndex(IntEnum):
	wdColorBlack = 1
	....
	
class WinWordColor(IntEnum):
	wdColorBlack = 0
	....

_highlightColors: Dict[WinWordColorIndex, WinWordColor) = {
```

File: source/speech/speech.py (hunk 4 above)
Comment (ABuffEr) [reply source/speech/speech.py:2448]: Like other attributes, it can be None if "highlight-color" key is absent.

File: nvdaHelper/remote/winword.cpp (hunk 3 above)
Comment (ABuffEr) [reply nvdaHelper/remote/winword.cpp]: I did it manually, I don't know how to run lint on .cpp files (runlint.bat seems to ignore them).

File: source/NVDAObjects/window/winword.py (hunk 5 above)
Comment (ABuffEr) [reply source/NVDAObjects/window/winword.py:223]: I'm not sure to have understood your proposal. After making enums, do you say to define _highlightColors as `{i.value: WinWordColor[i.name].value for i in WinWordColorIndex}`?

File: nvdaHelper/remote/winword.cpp (hunk 3 above)
Comment (seanbudd) [reply nvdaHelper/remote/winword.cpp]: yes, we don't have an automatic linting check for our C++

File: source/NVDAObjects/window/winword.py (hunk 5 above)
Comment (seanbudd) [reply source/NVDAObjects/window/winword.py:223]: yes exactly.

It also may be better named `_colorIndexToColor`

Comment (ABuffEr) [reply source/NVDAObjects/window/winword.py:223]: Ok, I'm proceeding. Just for clarity, to avoid reverting commits: I'll build WinWordColorIndex enum renaming i.e. wdBlack (as it would be in original enum) to wdColorBlack, and excluding reference-only values (wdByAuthor, wdAuto, wdNoHighlight). Then, in WinWordColor enum, I'll include just wdColor* useful for _colorIndexToColor mapping (16 against around 60). Right? Or do you prefer if I document all colors? (sorry for questions, this is my first PR)

Comment (seanbudd) [reply source/NVDAObjects/window/winword.py:223]: Yes, no need to map values that are not used in NVDA.

Your proposal makes sense.
It also may be worth dropping the `wdColor` prefix on the enum items, if you can do it consistently for all items.

**Comment by seanbudd** [comment]
Apologies, is this ready for review? This was marked as a draft.

File: nvdaHelper/remote/winword.cpp [hunk 6]
```diff
@@ -664,8 +674,12 @@ void generateXMLAttribsForFormatting(IDispatch* pDispatchRange, int startOffset,
 			}
 		}
 	}
-	int hlColorIndex=0;
-	if((formatConfig&formatConfig_reportHighlightColor)&&(_com_dispatch_raw_propget(pDispatchRange,wdDISPID_RANGE_HIGHLIGHTCOLORINDEX,VT_I4,&hlColorIndex)==S_OK)&&hlColorIndex>0) {
+	int hlColorIndex = 0;
+	if (
+		(formatConfig & formatConfig_reportHighlightColor)
+		&& (_com_dispatch_raw_propget(pDispatchRange, wdDISPID_RANGE_HIGHLIGHTCOLORINDEX, VT_I4, &hlColorIndex) == S_OK)
+		&& hlColorIndex>0
```
Comment (seanbudd) [inline nvdaHelper/remote/winword.cpp:681]: Added some linting:

```suggestion
		&& (hlColorIndex > 0)
```

**Review by seanbudd — APPROVED** [review]
This generally looks good to me.

**Comment by ABuffEr** [comment]
Hi @seanbudd,
with limitations I wrote in PR description (that I suggest to address separately), everything is ok for me.

File: nvdaHelper/remote/winword.cpp [hunk 7]
```diff
@@ -525,9 +526,28 @@ void generateXMLAttribsForFormatting(IDispatch* pDispatchRange, int startOffset,
...
+	if (
+		(formatConfig & formatConfig_reportColor)
+		|| (formatConfig & formatConfig_reportAlignment)
+		|| (formatConfig & formatConfig_reportParagraphIndentation)
+		|| (formatConfig & formatConfig_reportLineSpacing)
+	) {
 		IDispatchPtr pDispatchParagraphFormat=NULL;
 		if(_com_dispatch_raw_propget(pDispatchRange,wdDISPID_RANGE_PARAGRAPHFORMAT,VT_DISPATCH,&pDispatchParagraphFormat)==S_OK&&pDispatchParagraphFormat) {
+			if (formatConfig & formatConfig_reportColor) {
+				IDispatchPtr pDispatchParagraphFormatShading = NULL;
```
[the remark this answers is not in the document]
Comment (ABuffEr) [reply nvdaHelper/remote/winword.cpp:538]: I tried, but it becomes quite slow. And unlike excel.cpp, CComPtr is never used in winword.cpp, anyway.

[the remark this answers is not in the document]
Comment (seanbudd) [reply nvdaHelper/remote/winword.cpp:538]: yes but `IDispatchPtr` is only used in winword.cpp. In the long term, we should try and standardise our coding practices.
Could you explain what the performance differences are and how it affects the NVDA user?

[the remark this answers is not in the document]
Comment (ABuffEr) [reply nvdaHelper/remote/winword.cpp:538]: Using CComPtr I noticed a perceivable sluggish reply of NVDA simply reading single line paragraphs. Unfortunately I'm not so expert in C++ to explain the reasons or mreasure the difference. So even if I can agree with the standardization process, I cannot take care of mixing different typings/approaches.
