### PR TITLE
Get reliable points from offsets in virtual buffers

### LINKED ISSUE #6460: Incorrect offset points generated in tree interceptor text info
Steps to reproduce:
1. GO to nvaccess.org
2. Scroll to the text below the "What is NVDA" heading
3. Select the line below the heading
4. Start a python console
5. Do the following:
    >>> ti=nav.treeInterceptor.makeTextInfo("selection")
    >>> ti._startOffset
    323
    >>> ti._endOffset
    421
    >>> ti._getPointFromOffset(323).x
    401
    >>> ti._getPointFromOffset(323).y
    673
    >>> ti._getPointFromOffset(421).x
    401
    >>> ti._getPointFromOffset(421).y
    673

As you will notice, the x and y for both offsets are the same, which shouldn't be the case.

### LINKED ISSUE #7853: Filtering the elements lists sometimes results in one or more LookupError entries in the log
### Steps to reproduce:
1. Open www.nu.nl in either Firefox 58 or Chrome
2. Open the elements list
3. Press tab, and enter a word to filter on
4. Press shift+tab

### Expected behavior:
The list properly filters.

### Actual behavior:
Multiple LookupErrors are raised.

### System configuration:
NVDA version: Both 2017.4 and next
NVDA Installed or portable: Installed
Windows version: Windows 10 fall creators update

### Other questions:
Does the issue still occur after restarting your PC?
Not yet tested, but we should catch these LookupErrors anyway

### PR DESCRIPTION
**Pull request by LeonarddeR**
First of all, many thanks to @jcsteh for sharing his ideas with regard to how to implement this.

### Link to issue number:
Fixes #6460

### Summary of the issue:
When calculating the position of text in virtual buffers, NVDA uses the position of the object the text belongs to, rather than the real position of the offset you're retrieving the point for.

### Description of how this pull request fixes the issue:
1. Added two attributes to virtual buffer text nodes as discussed with @jcsteh:

    * ia2TextOffset: holds the start offset for a TextFieldNode within the IAccessibleText of its associated object. This attribute is only added to text field nodes that originate from IAccessibleText.
    * strippedCharsFromStart: When characters are stripped from the start of a text node (#2963) this attribute holds the amount of stripped chars from the start, in order for us to correct the ia2TextOffset.

2. the Gecko virtual buffer text info now has its own _getPointFromOffset implementation that uses the new virtual buffer attributes.
3. VirtualBufferTextInfo.getTextWithFields is now split up into a helper function _getFieldsInRange, similar to DisplayModelTextInfo. This allows for easy retrieval of control/format fields in a particular range, regardless where the text info is positioned.
4. pointFromOffset in the adobe acrobat virtual buffer now uses the _indexINParent attribute. It seems Adobe Acrobat has separate dom nodes for every word, so pointFromOffset now gets the center point of the word, which is far better than it was before.

### Testing performed:
* Tested several pages in Chrome and Firefox. Made sure that NVDA properly falls back to the center of an object when it has no text (i.e. a graphic or a link with an overridden aria-label).
* Tested with Adobe Reader 2018.011.20040. Though the implementation has some exception handling, testing with older versions might be a good thing to do. I have also tested with Adobe Reader XI, and This implementation  indeed, that doesn't provide per word objects.should handle that gracefully, though.

### Known issues with pull request:
* Chrome testing was somewhat limited because it seems that getOffsetFromPoint is broken for Chrome.

### Change log entry:
* Bug fixes
    + Moving the mouse to the navigator object will now much more accurately move the mouse to the browse mode position in Mozilla Firefox, Google Chrome and Acrobat Reader DC. (#6460)

### CODE REVIEW

**Comment by Adriani90** [comment]
fixes probably also #7915

**Comment by leonardder** [comment]
[**@Adriani90**](https://github.com/Adriani90) commented on [4 jul. 2018 15:34 CEST](https://github.com/nvaccess/nvda/pull/8479#issuecomment-402480856 "2018-07-04T13:34:06Z - Replied by Github Reply Comments"):
> fixes probably also #7915

Would you be able to verify that using [this](https://ci.appveyor.com/api/buildjobs/3o9n0cnw4l56bi48/artifacts/output%2Fnvda_snapshot_try-geckoPointFromOffset-15473%2C0895bdaa.exe) try build? Note that this try build doesn't contain the adobe code yet.

**Comment by Adriani90** [comment]
@leonardder I have tested the issues and got following results:

#6460: I cannot reproduce it at all, neither with NVDA 2018.2.1. But the webpage form NV Access has been redesigned. I tried different selections but I get different offset points for x and y, both at the start and at the end of the selection.

#7853: I confirm that your try build solves the issue.

#7915: unfortunately there is no improvement of mouse routing to navigator object in google chrome at all.

#7916: I guess the get OffsetFromPoint in MS Edge is broken as well. Mouse routing dows not work either.

**Comment by leonardder** [comment]
[**@Adriani90**](https://github.com/Adriani90) commented on [4 jul. 2018 22:20 CEST](https://github.com/nvaccess/nvda/pull/8479#issuecomment-402553702 "2018-07-04T20:20:27Z - Replied by Github Reply Comments"):
> #7915: unfortunately there is no improvement of mouse routing to navigator object in google chrome at all.

How did you test this?

**Comment by Adriani90** [comment]
I went on different websites and used object navigation. In Laptop layout, I pressed nvda+shift+m to route the mouse to the navigator object. But I didn‘t see any difference compared to NVDA 2018.2.1.


Von meinem iPhone gesendet

**Comment by leonardder** [comment]
Note that you should *not* use object navigation to test this, because that will always set the mouse to the start of the object you selected. You should just move the browse mode caret character by character or word by word and than move the mouse to the navigator object. This script description is actually confusing, as conceptually, the mouse is moved to the review position.

**Comment by Adriani90** [comment]
I have tested as you adviced. There is still the same behavior like in NVDA 2018.2.1. I have tried on google, hello magazine, NV Access and other websites. I have also tried  to route the mouse in focus and browse mode. It does not move the mouse to the object at all. It just reports "Window" or "Pane" but it does not behave like in firefox, or internet explorer where the mouse is routed much more accurately.

**Comment by Adriani90** [comment]
But there is a huge improvement in Mozilla Firefox, with your try build. The mouse can be routed from word to word which is quite reliable compared to NVDA 2018.2.1.

In Internet explorer and MS Edge there is no difference between NVDA 2018.2.1 and the try build.

**Comment by leonardder** [comment]
Edge will be dealt with in a subsequent pr, however that depends on #7537.

**Comment by Adriani90** [comment]
On some buttons on Github, when I try to route the mouse in Firefox, I get following error:

```
ERROR - scriptHandler.executeScript (19:26:22.085):
error executing script: <bound method GlobalCommands.script_moveMouseToNavigatorObject of <globalCommands.GlobalCommands object at 0x04F02A10>> with gesture u'Umschalt+NVDA+m'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "globalCommands.pyc", line 692, in script_moveMouseToNavigatorObject
  File "baseObject.pyc", line 21, in __get__
  File "textInfos\offsets.pyc", line 333, in _get_pointAtStart
  File "virtualBuffers\gecko_ia2.pyc", line 43, in _getPointFromOffset
  File "virtualBuffers\__init__.pyc", line 175, in _getPointFromOffset
TypeError: 'NoneType' object is not iterable
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (19:26:25.341):
Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.IAccessible object at 0x05233A30>
Python class mro: (<class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: None
value: None
appModule: <'firefox' (appName u'firefox', process ID 13872) at address 50bdc10>
appModule.productName: u'Firefox'
appModule.productVersion: u'60.0.2'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 197640
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 7908
windowText: u'Get reliable points from offsets in virtual buffers by leonardder \xb7 Pull Request #8479 \xb7 nvaccess/nvda - Mozilla Firefox'
displayText: exception: 'NoneType' object is not iterable
IAccessibleObject: <POINTER(IAccessible) ptr=0x6866d00 at 51a6210>
IAccessibleChildID: -33560358
IAccessible event parameters: windowHandle=197640, objectID=-4, childID=-33560358
IAccessible accName: exception: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
IAccessible accRole: exception: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
IAccessible accState: exception: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
IAccessible accDescription: exception: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
IAccessible accValue: exception: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
```

The buttons are:
Add header text
Add bold text <ctrl+b>
Add italic text <ctrl+i>
 
Insert a quote
Insert code
Add a link <ctrl+k>
 
Add a bulleted list
Add a numbered list
Add a task list

Directly mention a user or team
Reference an issue or pull request
"Menu button" Insert a reply

**Comment by Adriani90** [comment]
on the top of the github page, for some elements I get following error:

```
ERROR - eventHandler.executeEvent (19:31:24.341):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x052BA7B0> with extra args of {'y': 251, 'x': 3200}
Traceback (most recent call last):
  File "eventHandler.pyc", line 152, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 930, in event_mouseMove
  File "NVDAObjects\IAccessible\__init__.pyc", line 145, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
```

This is the case for following elements:

Link Homepage


Button Create new…
Button View profile and more

**Comment by Adriani90** [comment]
The attribute "Rindex" error appears in Google Chrome everytime as well.

**Comment by Adriani90** [comment]
In Edge I don't get any entry in the log file unfortunately, there is no input registered.
The mouse routing in Edge seems to fail on simple text and in the footer of the websites.

**Comment by Adriani90** [comment]
In Internet explorer there is also no entry in the log file when mouse routing fails.

**Comment by leonardder** [comment]
[**@Adriani90**](https://github.com/Adriani90) commented on [5 jul. 2018 19:32 CEST](https://github.com/nvaccess/nvda/pull/8479#issuecomment-402797297 "2018-07-05T17:32:05Z - Replied by Github Reply Comments"):
> On some buttons on Github, when I try to route the mouse in Firefox, I get following error:

AH, this bug was already there actually. Fixed it while at it.

> on the top of the github page, for some elements I get following error:

Hmm this error seems to be quite unrelated to this pr.

> In Edge I don't get any entry in the log file...

Could you please limit your comments and reports to the scope of this pr, thus, adobe reader, Firefox and Chrome? As I noted earlier, Edge will be dealt with at a later moment. For Internet Explorer, I"m afraid there's nothing we can do to improve mouse tracking.

File: nvdaHelper/vbufBase/storage.cpp [hunk 1]
```diff
@@ -579,6 +579,13 @@ VBufStorage_textFieldNode_t*  VBufStorage_buffer_t::addTextFieldNode(VBufStorage
 		delete textFieldNode;
 		return NULL;
 	}
+	if (needsStrip && subStart>0) {
+		// There are characters stripped from the start of the text.
+		// We save these characters in an attribute, required for calculating offsets in IA2Text.
```
Comment (jcsteh) [inline nvdaHelper/vbufBase/storage.cpp]: nit: This comment makes it seem like we're saving the characters themselves, not the number of characters. Please clarify.

File: source/NVDAObjects/IAccessible/__init__.py [hunk 2]
```diff
@@ -124,7 +124,9 @@ def _getPointFromOffset(self,offset):
 			res=self.obj.IAccessibleTextObject.characterExtents(offset,IAccessibleHandler.IA2_COORDTYPE_SCREEN_RELATIVE)
 		except COMError:
 			raise NotImplementedError
-		point=textInfos.Point(res[0]+(res[2]/2),res[1]+(res[3]/2))
+		# Using the center of the character's bounding rectangle could result in a point
+		# of which IA2 believes that it belongs to a higher offset.
```
Comment (jcsteh) [inline source/NVDAObjects/IAccessible/__init__.py]: 1. Did you see this bug in Firefox? IMO, this is an implementation bug; the centre of a character should be treated as part of that character. I guess this should be safe enough for characters, though. It can get nasty with objects due to borders, etc., which is why we tend to use the centre. Anyway, it might be worth noting in the comment that you saw this bug occur in Firefox.
2. How does this bug actually manifest from a user perspective? I assume clicking does click the right character, but maybe mouse tracking reports the wrong one?
3. It's not clear why you're talking about the centre here unless you're reading this diff. Perhaps you could preface it with "Normally, we tend to use the centre point of a bounding rectangle."

File: source/virtualBuffers/__init__.py [hunk 3]
```diff
@@ -135,11 +135,12 @@ class VirtualBufferTextInfo(browseMode.BrowseModeDocumentTextInfo,textInfos.offs
 	allowMoveToOffsetPastEnd=False #: no need for end insertion point as vbuf is not editable. 
 
 	UNIT_CONTROLFIELD = "controlField"
+	UNIT_FORMATFIELD = "formatField"
 
 	def _getControlFieldAttribs(self,  docHandle, id):
-		info = self.copy()
-		info.expand(textInfos.UNIT_CHARACTER)
-		for field in reversed(info.getTextWithFields()):
+		start, end = self._getOffsetsFromFieldIdentifier(docHandle, id)
```
Comment (jcsteh) [inline source/virtualBuffers/__init__.py]: > `VirtualBufferTextInfo._getControlFieldAtribs` now utilizes the new `_getFieldsInRange` method. The new implementation adds an extra rpc call, but no longer creates a copy of the text info. Honestly the current implementation makes much more sense to me and hopefully fixes #7853.

1. Copying a TextInfo is super cheap (it just copies the offsets). An RPC call is not so cheap. I'm worried this could cause significant performance degradation in the Elements List, since we're obtaining TextInfos for all of those elements but then querying their offsets again. At the very least, the performance needs to be tested on big documents before and after this patch.
2. Why do you think this will fix #7853? The TextInfos created for VirtualBufferQuickNavItems use the same RPC call to fetch offsets. It's possible the offsets shift once the Elements List appears (perhaps due to focus listing), but in that case, the TextInfo will also be broken and we need to re-fetch that too. (Otherwise, move and activate will be broken; I think there are other bugs filed about that.)

I understand why you need a way to do this given arbitrary offsets, but I'm not convinced we always want to fetch the offsets if we know the object is definitely within the TextInfo. Perhaps the method could take a `fieldWithinTextInfo=False` argument or similar and not fetch the offsets in that case.

File: source/virtualBuffers/__init__.py [hunk 4]
```diff
@@ -334,6 +342,10 @@ def _normalizeControlField(self,attrs):
 		return attrs
 
 	def _normalizeFormatField(self, attrs):
+		strippedCharsFromStart = attrs.get("strippedCharsFromStart")
+		if strippedCharsFromStart is not None:
+			assert strippedCharsFromStart.isdigit, "strippedCharsFromStart is no digit, %r" % strippedCharsFromStart
```
Comment (jcsteh) [inline source/virtualBuffers/__init__.py]: 1. That should be `isdigit()` (method call), not just `isdigit` (attribute). `isdigit` will always be True. :)
2. nit: "is no digit" -> "is not a digit"

File: source/virtualBuffers/adobeAcrobat.py [hunk 5]
```diff
@@ -18,6 +18,30 @@
...
+			attrs = field.field
+			indexInParent = attrs.get("_indexInParent")
+			if indexInParent is None:
+				continue
+			try:
+				obj = self._getNVDAObjectFromOffset(offset).getChild(indexInParent)
+			except IndexError:
+				obj = None
+			if not obj:
+				continue
```
Comment (jcsteh) [inline source/virtualBuffers/adobeAcrobat.py]: nit: You could simplify this by just doing "continue" within the except block.

File: source/virtualBuffers/gecko_ia2.py [hunk 6]
```diff
@@ -18,10 +18,58 @@
...
+				# This is no format field.
+				continue
+			attrs = field.field
+			ia2TextStartOffset = attrs.get("ia2TextStartOffset")
+			if ia2TextStartOffset is None:
+				continue
+			ia2TextStartOffset += attrs.get("strippedCharsFromStart", 0)
+			relOffset = offset - formatFieldStart + ia2TextStartOffset
+			obj = self._getNVDAObjectFromOffset(offset)
+			if not issubclass(obj.TextInfo, IA2TextTextInfo):
```
Comment (jcsteh) [inline source/virtualBuffers/gecko_ia2.py]: Have you tested this within a text box? The TextInfo in that case will be `MozillaCompoundTextInfo`, so this will fail. I think you need to use IA2 text directly here. See below for further thoughts on that.

File: source/virtualBuffers/gecko_ia2.py [hunk 7]
```diff
@@ -18,10 +18,58 @@
...
+				raise LookupError("TextInfo is of type %r and does not provide reliable points" % obj.TextInfo)
+			# Position is irrelevant here, we just need a text info to work with
+			info = obj.makeTextInfo(textInfos.POSITION_FIRST)
+			return info._getPointFromOffset(relOffset)
```
Comment (jcsteh) [inline source/virtualBuffers/gecko_ia2.py]: I'm not a fan of having to instantiate this here, especially given the above. Perhaps you could make this a classmethod or split it into a helper function. The former should work, but would need testing. (You should be able to get away with only making it a classmethod for that one TextInfo, rather than the whole of NVDA.)

File: source/virtualBuffers/gecko_ia2.py [hunk 8]
```diff
@@ -18,10 +18,58 @@
...
+		if not obj or not issubclass(obj.TextInfo, IA2TextTextInfo):
+			raise LookupError
+		# Find out whether this object contains text that has been stripped in the virtual buffer.
+		for field in reversed(self._getFieldsInRange(start, start+1)):
+			if not (isinstance(field, textInfos.FieldCommand) and field.command == "formatChange"):
+				# This is no format field.
+				continue
+			strippedCharsFromStart = field.field.get("strippedCharsFromStart")
+			if strippedCharsFromStart is not None:
+				break
```
Comment (jcsteh) [inline source/virtualBuffers/gecko_ia2.py]: This assumes there's only one text field in the object. Normally, this should be true, since you start with the deepest object. However, there are cases where we might not render something into the buffer; e.g. where aria-label overrides the subtree, list box items, etc. There's probably no point in doing the stripped chars search if you have to walk to the parent (unless getNVDAObjectFromPoint returns text leaf nodes, in which case you'll always have to walk one parent).

File: source/virtualBuffers/gecko_ia2.py [hunk 9]
```diff
@@ -18,10 +18,58 @@
...
+		else:
+			strippedCharsFromStart = 0
+		relOffset = obj.makeTextInfo(textInfos.Point(x, y))._startOffset
```
Comment (jcsteh) [inline source/virtualBuffers/gecko_ia2.py]: Same concern about MozillaCompoundTextInfo as above.

File: source/virtualBuffers/gecko_ia2.py [hunk 10]
```diff
@@ -84,7 +132,11 @@ def _normalizeControlField(self,attrs):
 
 	def _normalizeFormatField(self, attrs):
 		normalizeIA2TextFormatField(attrs)
-		return attrs
+		ia2TextStartOffset = attrs.get("ia2TextStartOffset")
+		if ia2TextStartOffset is not None:
+			assert ia2TextStartOffset.isdigit, "ia2TextStartOffset is no digit, %r" % ia2TextStartOffset
```
Comment (jcsteh) [inline source/virtualBuffers/gecko_ia2.py]: See concerns re isdigit above.

**Review by jcsteh — CHANGES_REQUESTED** [review]

File: source/virtualBuffers/__init__.py (hunk 3 above)
Comment (jcsteh) [reply source/virtualBuffers/__init__.py]: Err, I meant focus moving, not focus listing.

**Comment by jcsteh** [comment]
Ah. If getChild can return None or throw an exception, just leave the code you originally had. Sorry; I should've realised that.

And you're right, it has to be a helper. Or you could probably just duplicate the code even. It's pretty short. I'd accept either.

File: source/virtualBuffers/gecko_ia2.py (hunk 8 above)
Comment (leonardder) [reply source/virtualBuffers/gecko_ia2.py]: I"m not sure what you are asking here. I understand your point that an object could have multiple text fields, but are you suggesting not to do the stripped chars search in some cases?

File: source/virtualBuffers/gecko_ia2.py [hunk 11]
```diff
@@ -56,16 +56,13 @@ def _getOffsetFromPoint(self,x,y):
 		if not obj or not hasattr(obj, "IAccessibleTextObject"):
 			raise LookupError
 		# Find out whether this object contains text that has been stripped in the virtual buffer.
-		for field in reversed(self._getFieldsInRange(start, start+1)):
+		relOffset = IA2TextTextInfo._getOffsetFromPointInObject(obj, x, y)
+		strippedCharsFromStart = 0
+		for field in reversed(self._getFieldsInRange(start, min(end-1, start+relOffset))):
```
Comment (jcsteh) [inline source/virtualBuffers/gecko_ia2.py]: This method could still break... and it's actually worse than I originally thought; it affects more than just stripped char searching. You're assuming the text offsets in the buffer match the IA2 text offsets. This won't be true in several cases:

1. The target text has an embedded object before it. In that case, the embedded object will consume one IA2 offset, but in the buffer, the content of the embedded object will be rendered. For example:

    `data:text/html,<p><a href="https://mozilla.org">link</a>text</p>`

    Imagine your mouse is over the first letter "t" in text. That's IA2 offset 1 in the paragraph, but in the buffer, that's actually offset 4.

2. The target object isn't in the buffer; e.g. listbox items or subtree overridden by aria-label. You get around this by walking the object's parents... but now you might be dealing with a completely different object, and thus the offsets are no longer referring to the same thing. Example:

    `data:text/html,<h1 aria-label="h1"><a href="https://mozilla.org">link</a></h1>`

    If your mouse is on the "n" of link, that's IA2 offset 2, but that character doesn't even exist in the buffer, nor does the offset.

So:

1. You need to be looking at the IA2 offsets in the buffer (and the stripped chars), as well as restricting the search to the same object.
2. If the object isn't in the buffer (aside from text leaf nodes where going parent is safe), you should probably just return the first offset for the nearest ancestor.

**Review by jcsteh — CHANGES_REQUESTED** [review]

File: source/virtualBuffers/gecko_ia2.py (hunk 11 above)
Comment (leonardder) [reply source/virtualBuffers/gecko_ia2.py]: Hmm, it turns out that this code is quite hard to test anyway. I'm leaning towards removing it for now, it is not strictly necessary for virtual buffers to get offsets from point, as mouse echo functions at the object level and doesn't deal with tree interceptors.

**Review by jcsteh — CHANGES_REQUESTED** [review]
Thanks. Nearly there. One more thing:

File: source/NVDAObjects/IAccessible/__init__.py [hunk 12]
```diff
@@ -114,20 +114,34 @@ class IA2TextTextInfo(textInfos.offsets.OffsetsTextInfo):
 
 	detectFormattingAfterCursorMaybeSlow=False
 
-	def _getOffsetFromPoint(self,x,y):
-		if self.obj.IAccessibleTextObject.nCharacters>0:
-			return self.obj.IAccessibleTextObject.OffsetAtPoint(x,y,IAccessibleHandler.IA2_COORDTYPE_SCREEN_RELATIVE)
+	@classmethod
+	def _getOffsetFromPointInObject(cls,obj,x,y):
```
[the remark this answers is not in the document]
Comment (leonardder) [reply source/NVDAObjects/IAccessible/__init__.py]: Fixed, thanks for catching that.

**Review by jcsteh — DISMISSED** [review]
Thanks! And sorry we had so many rounds of review. :)

**Review by michaelDCurran — DISMISSED** [review]

**Comment by michaelDCurran** [comment]
@leonardder: I don't understand one of your mentioned tests:
"I have also tested with Adobe Reader XI, and This implementation indeed, that doesn't provide per word objects.should handle that gracefully, though."
Does this work or does this not work?
If you're happy for this to go into master, please update changes.t2t and I will merge it.

**Comment by leonardder** [comment]
[**@michaelDCurran**](https://github.com/michaelDCurran) commented on [3 Aug 2018, 05:52 CEST](https://github.com/nvaccess/nvda/pull/8479#issuecomment-410136929 "2018-08-03T03:52:40Z - Replied by Github Reply Comments"):
> @leonardder: I don't understand one of your mentioned tests:
> "I have also tested with Adobe Reader XI, and This implementation indeed, that doesn't provide per word objects.should handle that gracefully, though."
> Does this work or does this not work?
> If you're happy for this to go into master, please update changes.t2t and I will merge it.

Wow, it looks like my cursor was going mad there.

That sentence should've been

> "I have also tested with Adobe Reader XI, and indeed, that doesn't provide per word objects. This implementation should handle that gracefully, though."

So no, it does not work with older versions, but it shouldn't get worse than it is now.

Having said that though, I'd like some additional testing before this lands in master. Some testing from sighted people, may be @qchistensen or @feerrenrut, would be very helpful.
[Here](https://ci.appveyor.com/api/buildjobs/oft4s2mavs2ubdc8/artifacts/output%2Fnvda_snapshot_try-geckoPointFromOffset-15775%2C99d3d027.exe) is a try build.

Testing steps.

1. Open a document in Firefox, Chrome or Adobe Reader
2. Use browse mode to place the browse mode caret at some text
3. Use the mouse move to navigator object command to move the mouse
4. Make sure that the mouse lands on the exact character (firefox/Chrome) or word (adobe reader) that you've selected, respectively.

I'm pretty sure that Chrome might be buggier than Firefox, but again, it shouldn't make things worse than they were before.

**Comment by feerrenrut** [comment]
I have had a go with this.

In firefox, the mouse is moved to the upper left corner of the letter or word that the virtual cursor is at. I wonder if it would be better to center it? After NVDA moves the mouse the paragraph is read out, I am actually not sure what the original behaviour is here, but I found this a little disconcerting. After hearing selecting a letter in a word, then moving the mouse there, I would expect confirmation of where the mouse moved. 

In Adobe reader, the mouse is centered on the word. Also reads the paragraph

In chrome, the mouse is also moved to the upper left corner of the letter or word. Does not seem to read the paragraph, just the application / window title / document name?

**Comment by leonardder** [comment]
[**@feerrenrut**](https://github.com/feerrenrut) commented on [6 aug. 2018 09:40 CEST](https://github.com/nvaccess/nvda/pull/8479#issuecomment-410616849 "2018-08-06T07:40:42Z - Replied by Github Reply Comments"):
> In firefox, the mouse is moved to the upper left corner of the letter or word that the virtual cursor is at. I wonder if it would be better to center it? 

That is possible, yes. However, at some websites, it seemed that the cursor ended up at the wrong letter when using the center's point. I will build another try build with this though.

> After NVDA moves the mouse the paragraph is read out, 

You can change this in NVDA's mouse settings, setting the resolution to character or word.

> After hearing selecting a letter in a word, then moving the mouse there, I would expect confirmation of where the mouse moved.'

Yes, that is, when mouse tracking is on and you selected the desired text unit resolution. Note that, if NVDA somehow reads the wrong information, this is strictly spoken unrelated, i.e. getPointFromOffset is used when the mouse is moved to a particular character, and getOffsetFromPoint is used when calculating the offset a character belongs to. Offset from point calculation happens at the object level, not add the tree interceptor/virtual buffer level.

> In Adobe reader, the mouse is centered on the word. Also reads the paragraph

That is great :)
 
> In chrome, the mouse is also moved to the upper left corner of the letter or word. Does not seem to read the paragraph, just the application / window title / document name?

Now this seems to be a bug where Chrome seems to be unable to get an offset from a particular point.

**Comment by leonardder** [comment]
[Here](https://ci.appveyor.com/api/buildjobs/lbg83m4o9fvb2fa1/artifacts/output%2Fnvda_snapshot_try-geckoPointFromOffset-15793%2Cc19970ec.exe) is a try build that should move the mouse to the center of the characters in Firefox and Chrome.

File: source/NVDAObjects/IAccessible/__init__.py [hunk 13]
```diff
@@ -120,14 +120,24 @@ def _getOffsetFromPoint(self,x,y):
...
-	def _getPointFromOffset(self,offset):
+	@classmethod
+	def _getPointFromOffsetInObject(cls,obj,offset):
 		try:
-			res=self.obj.IAccessibleTextObject.characterExtents(offset,IAccessibleHandler.IA2_COORDTYPE_SCREEN_RELATIVE)
+			res=obj.IAccessibleTextObject.characterExtents(offset,IAccessibleHandler.IA2_COORDTYPE_SCREEN_RELATIVE)
 		except COMError:
 			raise NotImplementedError
+		# Normally, L{_getPointFromOffset} implementations that rely on
+		# character bounding rectangles use the center point of the rectangle.
```
Comment (feerrenrut) [inline source/NVDAObjects/IAccessible/__init__.py]: Is this comment still correct? It makes it sound like this will not use the center, which is what it appears to do.

**Comment by feerrenrut** [comment]
I'm testing out this new build (nvda_snapshot_try-geckoPointFromOffset-15793,c19970ec.exe)

Indeed in chrome and firefox the middle of the word / character is now selected.

> After NVDA moves the mouse the paragraph is read out,

> You can change this in NVDA's mouse settings, setting the resolution to character or word.

One point is that I do not have mouse tracking enabled, should it still read the paragraph? The amount reported does obey the resolution setting.

> Yes, that is, when mouse tracking is on and you selected the desired text unit resolution. Note that, if NVDA somehow reads the wrong information, this is strictly spoken unrelated, i.e. getPointFromOffset is used when the mouse is moved to a particular character, and getOffsetFromPoint is used when calculating the offset a character belongs to. Offset from point calculation happens at the object level, not add the tree interceptor/virtual buffer level.

For some reason I can't seem to get anything intelligible when using `Navigate to the object under the mouse` I wanted to test that selecting the center (rather than the top left) does not break `getOffsetFromPoint` for the same position. I think that the behaviour of these should be symmetrical.

**Comment by leonardder** [comment]
[**@feerrenrut**](https://github.com/feerrenrut) commented on [7 aug. 2018 06:48 CEST](https://github.com/nvaccess/nvda/pull/8479#issuecomment-410932118 "2018-08-07T04:48:02Z - Replied by Github Reply Comments"):
> > After NVDA moves the mouse the paragraph is read out,
> 
> > You can change this in NVDA's mouse settings, setting the resolution to character or word.
> 
> One point is that I do not have mouse tracking enabled, should it still read the paragraph? The amount reported does obey the resolution setting.

Hmm yes, it turns out that disabling mouse tracking will still report mouse changes triggered by NVDA. I did not expect this honestly, and I'm not sure whether this is defined behavior. I'd expect it not to do this.

> For some reason I can't seem to get anything intelligible when using `Navigate to the object under the mouse` I wanted to test that selecting the center (rather than the top left) does not break `getOffsetFromPoint` for the same position. I think that the behaviour of these should be symmetrical.

I tend to use [this website](http://www.toastsoft.net/) for testing random things. Try the text that reads "Similarly, the open-ended nature of the game" for example. That will report the character that belongs to offset+1 when I move the mouse to the text. Now, your eyes should be able to determine whether pointFromOffset or offsetFromPoint fails here.

**Comment by jcsteh** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [Aug 7, 2018, 3:14 PM GMT+10](https://github.com/nvaccess/nvda/pull/8479#issuecomment-410935645 "2018-08-07T05:14:12Z - Replied by Github Reply Comments"):
> Hmm yes, it turns out that disabling mouse tracking will still report mouse changes triggered by NVDA. I did not expect this honestly, and I'm not sure whether this is defined behavior. I'd expect it not to do this.

I can't remember whether there was a filed issue for this change, but without this behaviour, moving mouse to review would just report nothing when mouse tracking is disabled. Silence is confusing/misleading here, IMO. We could report "Moved" or something, but if we're going to do that, we may as well report where it moved.

**Comment by feerrenrut** [comment]
Using your link, and arrowing around (to the last letter of "players are free to attack at will") moving the mouse to the 'L' with "Move mouse to current navigator object", and using the "Navigate to the object under the mouse" then "Paragraph" is reported. Pressing "Report current word in review" and "Similarly," is reported. Which is the start of the paragraph. I don't know how to report the word under the mouse in this way.

> We could report "Moved" or something, but if we're going to do that, we may as well report where it moved.

I'm happy with this, perhaps we can document it somewhere as part of this pull request? Also that the amount reported does obey the resolution setting in the mouse setting dialog.

**Comment by leonardder** [comment]
[**@feerrenrut**](https://github.com/feerrenrut) commented on [7 aug. 2018 11:48 CEST](https://github.com/nvaccess/nvda/pull/8479#issuecomment-411000197 "2018-08-07T09:48:11Z - Replied by Github Reply Comments"):
> Using your link, and arrowing around (to the last letter of "players are free to attack at will") moving the mouse to the 'L' with "Move mouse to current navigator object", and using the "Navigate to the object under the mouse" then "Paragraph" is reported. Pressing "Report current word in review" and "Similarly," is reported. Which is the start of the paragraph. I don't know how to report the word under the mouse in this way.

Does the mouse end up at the exact center position of the "L" though?

**Comment by feerrenrut** [comment]
> Does the mouse end up at the exact center position of the "L" though?

Yes, in Firefox and Chrome. In Adobe reader the mouse moves to the center of the word as expected.

**Comment by leonardder** [comment]
@feerrenrut: Are you done with reviewing this, or have I missed something that I haven't yet addressed?

**Review by feerrenrut — DISMISSED** [review]
Yep, this looks good.
