### PR TITLE
Fix access to content of 64-bit syslistview32 controls

### LINKED ISSUE #8175: No item names for some listviews (64-bit)
### Steps to reproduce:
Example app: Tortoise SVN

- invoke a context command such as SVN Update on a local repo.
- A window appears with the progress made so far.
- Tab to the list and try to navigate.
- one or multiple  error sounds are issued.

### Expected behavior:
The name of the focused item should be announced.

### Actual behavior:
Only the state (e.g. selected) is announced

### System configuration:
NVDA version next-15028,2754a2c8
Installed/Source/portable

Windows 10 (x64), Version 1803 (OS Build 17133.73)

Name and version of other software in use when reproducing the issue:
Tortoise SVN 1.9.7.27907 x64
### Other questions:

Does the issue still occur after restarting your PC?

Yes

Have you tried any other versions of NVDA?

Not relevant

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Supersedes #8190
Fixes #8175

### Summary of the issue:
For some list view controls in 64-bit programs, most notably TortoiseSVN, NVDA is unable to output the list items.

### Description of how this pull request fixes the issue:
Adds an in process implementation to fetch column contents.

### Testing performed:
Tested that output works in 64-bit TortoiseSVN list views when commuting changes.

### Known issues with pull request:
See  in line code comment.

### Change log entry:
* Bug fixes
    - NVDA no longer fails to read items in list views within a 64-bit application such as Tortoise SVN. (#8175)

### CODE REVIEW

File: nvdaHelper/remote/sysListView32.cpp [hunk 1]
```diff
@@ -33,3 +33,23 @@ error_status_t nvdaInProcUtils_sysListView32_getGroupInfo(handle_t bindingHandle
...
 	return 0;
 }
+
+error_status_t nvdaInProcUtils_sysListView32_getColumnContent(handle_t bindingHandle, const unsigned long windowHandle, int item, int subItem, BSTR* text) {
+	LVITEM lvItem = {0};
+	lvItem.mask = LVIF_TEXT | LVIF_COLUMNS;
+	lvItem.iItem = item;
+	lvItem.iSubItem = subItem;
+	lvItem.cchTextMax = 512;
+	wchar_t textBuf[512];
```
Comment (leonardder) [inline nvdaHelper/remote/sysListView32.cpp:43]: I wonder whether this will be cleaned up correctly after use. Is there a better approach?

**Review by michaelDCurran — DISMISSED** [review]

File: nvdaHelper/remote/sysListView32.cpp (hunk 1 above)
Comment (michaelDCurran) [reply nvdaHelper/remote/sysListView32.cpp]: That buffer is just an array on the stack. That memory will go away once the function returns.

**Comment by codeofdusk** [comment]
@michaelDCurran @feerrenrut Did you intend to merge this?
